#Importando Bibliotecas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Configuração
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Importando base de dados

In [3]:
dados = pd.read_csv('/content/BAS_base_dados - TABELA FILTRADA.csv')

/tmp/ipython-input-4128847507.py:1: DtypeWarning: Columns (57) have mixed types. Specify dtype option on import or set low_memory=False.
  dados = pd.read_csv('/content/BAS_base_dados - TABELA FILTRADA.csv')

#Analise explanatória

In [4]:
dados.head()

,npf,data,nome_sessao,quarto_jg,codigo,vel_max,sprints,dits_total,zv1,zv2,zv3,zv4,zv5,dai,dmi,dcel4,dcel3,dcel2,dcel1,acel1,acel2,acel3,acel4,fc1,fc2,fc3,fc4,fc5,fc_80,trimp,tempo,sprints_min,dits_total_min,zv1_min,zv2_min,zv3_min,zv4_min,zv5_min,dai_min,dmi_min,dcel4_min,dcel3_min,dcel2_min,dcel1_min,acel1_min,acel2_min,acel3_min,acel4_min,fc1_min,fc2_min,fc3_min,fc4_min,fc5_min,fc_80_min,trimp_min,adversario,idade,quarto,classificacao,interv_dias,mando,posicao,temp,placar_mtc,placar_adv,dif,dif_modolo,Competição
0,676677,10/11/2020,20.11.10_Flamengo,1º Quarto,20.11.10_Flamengo1º Quarto676677,"5,9",0,83,69,0,0,0,0,0,0.0,0,0,28,4,3,29,0,0,17,0,0,0,0,0,17,"0,0",#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,Flamengo,"18,00",1,1.0,6.0,3,3,20/21,68,102,-34,34,NBB
1,676677,10/11/2020,20.11.10_Flamengo,3º Quarto,20.11.10_Flamengo3º Quarto676677,"14,4",0,232,135,54,28,0,0,0,28.0,0,1,19,13,13,17,2,0,3,1,0,0,0,0,5,"0,0",#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,Flamengo,"18,00",3,1.0,6.0,3,3,20/21,68,102,-34,34,NBB
2,699947,10/11/2020,20.11.10_Flamengo,4º Quarto,20.11.10_Flamengo4º Quarto699947,"4,9",0,30,25,0,0,0,0,0,0.0,0,0,2,4,3,3,0,0,11,0,0,0,0,0,11,"0,0",#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,#DIV/0!,Flamengo,"26,00",4,1.0,6.0,3,3,20/21,68,102,-34,34,NBB
3,690318,10/11/2020,20.11.10_Flamengo,3º Quarto,20.11.10_Flamengo3º Quarto690318,"26,1",12,1741,573,620,364,119,14,133,497.0,4,30,118,79,70,115,33,0,0,1,4,9,9,18,94,"10,0","1,2","174,1","57,3","62,0","36,4","11,9","1,4","13,3","49,7","0,4","3,0","11,8","7,9","7,0","11,5","3,3","0,0","0,0","0,1","0,4","0,9","0,9","1,8","9,4",Flamengo,"18,00",3,1.0,6.0,3,3,20/21,68,102,-34,34,NBB
4,696806,10/11/2020,20.11.10_Flamengo,2º Quarto,20.11.10_Flamengo2º Quarto696806,"29,3",17,2019,761,655,383,104,27,131,514.0,15,30,159,107,106,129,49,2,0,1,6,6,16,22,125,"10,0","1,7","201,9","76,1","65,5","38,3","10,4","2,7","13,1","51,4","1,5","3,0","15,9","10,7","10,6","12,9","4,9","0,2","0,0","0,1","0,6","0,6","1,6","2,2","12,5",Flamengo,"28,00",2,1.0,6.0,3,1,20/21,68,102,-34,34,NBB

In [5]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9006 entries, 0 to 9005
Data columns (total 68 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   npf             9006 non-null   int64
 1   data            9006 non-null   object
 2   nome_sessao     9006 non-null   object
 3   quarto_jg       9006 non-null   object
 4   codigo          9006 non-null   object
 5   vel_max         9006 non-null   object
 6   sprints         9006 non-null   int64
 7   dits_total      9006 non-null   int64
 8   zv1             9006 non-null   int64
 9   zv2             9006 non-null   int64
 10  zv3             9006 non-null   int64
 11  zv4             9006 non-null   int64
 12  zv5             9006 non-null   int64
 13  dai             9006 non-null   int64
 14  dmi             8806 non-null   float64
 15  dcel4           9006 non-null   int64
 16  dcel3           9006 non-null   int64
 17  dcel2           9006 non-null   int64
 18  dcel1           9006 non-null   int64
 19  acel1           9006 non-null   int64
 20  acel2           9006 non-null   int64
 21  acel3           9006 non-null   int64
 22  acel4           9006 non-null   int64
 23  fc1             9006 non-null   int64
 24  fc2             9006 non-null   int64
 25  fc3             9006 non-null   int64
 26  fc4             9006 non-null   int64
 27  fc5             9006 non-null   int64
 28  fc_80           9006 non-null   int64
 29  trimp           9006 non-null   int64
 30  tempo           8920 non-null   object
 31  sprints_min     9006 non-null   object
 32  dits_total_min  9006 non-null   object
 33  zv1_min         9006 non-null   object
 34  zv2_min         9006 non-null   object
 35  zv3_min         9006 non-null   object
 36  zv4_min         9006 non-null   object
 37  zv5_min         9006 non-null   object
 38  dai_min         9006 non-null   object
 39  dmi_min         8806 non-null   object
 40  dcel4_min       9006 non-null   object
 41  dcel3_min       9006 non-null   object
 42  dcel2_min       9006 non-null   object
 43  dcel1_min       9006 non-null   object
 44  acel1_min       9006 non-null   object
 45  acel2_min       9006 non-null   object
 46  acel3_min       9006 non-null   object
 47  acel4_min       9006 non-null   object
 48  fc1_min         9006 non-null   object
 49  fc2_min         9006 non-null   object
 50  fc3_min         9006 non-null   object
 51  fc4_min         9006 non-null   object
 52  fc5_min         9006 non-null   object
 53  fc_80_min       9006 non-null   object
 54  trimp_min       9006 non-null   object
 55  adversario      9006 non-null   object
 56  idade           9006 non-null   object
 57  quarto          9006 non-null   object
 58  classificacao   8828 non-null   float64
 59  interv_dias     8918 non-null   float64
 60  mando           9006 non-null   int64
 61  posicao         9006 non-null   int64
 62  temp            9006 non-null   object
 63  placar_mtc      9006 non-null   int64
 64  placar_adv      9006 non-null   int64
 65  dif             9006 non-null   int64
 66  dif_modolo      9006 non-null   int64
 67  Competição      9006 non-null   object
dtypes: float64(3), int64(30), object(35)
memory usage: 4.7+ MB

In [6]:
dados.isnull().sum()

npf                 0
data                0
nome_sessao         0
quarto_jg           0
codigo              0
vel_max             0
sprints             0
dits_total          0
zv1                 0
zv2                 0
zv3                 0
zv4                 0
zv5                 0
dai                 0
dmi               200
dcel4               0
dcel3               0
dcel2               0
dcel1               0
acel1               0
acel2               0
acel3               0
acel4               0
fc1                 0
fc2                 0
fc3                 0
fc4                 0
fc5                 0
fc_80               0
trimp               0
tempo              86
sprints_min         0
dits_total_min      0
zv1_min             0
zv2_min             0
zv3_min             0
zv4_min             0
zv5_min             0
dai_min             0
dmi_min           200
dcel4_min           0
dcel3_min           0
dcel2_min           0
dcel1_min           0
acel1_min           0
acel2_min           0
acel3_min           0
acel4_min           0
fc1_min             0
fc2_min             0
fc3_min             0
fc4_min             0
fc5_min             0
fc_80_min           0
trimp_min           0
adversario          0
idade               0
quarto              0
classificacao     178
interv_dias        88
mando               0
posicao             0
temp                0
placar_mtc          0
placar_adv          0
dif                 0
dif_modolo          0
Competição          0
dtype: int64

In [7]:
dados.describe()

,npf,sprints,dits_total,zv1,zv2,zv3,zv4,zv5,dai,dmi,dcel4,dcel3,dcel2,dcel1,acel1,acel2,acel3,acel4,fc1,fc2,fc3,fc4,fc5,fc_80,trimp,classificacao,interv_dias,mando,posicao,placar_mtc,placar_adv,dif,dif_modolo
count,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000,8806.000000,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000,8828.000000,8918.000000,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000,9006.000000
mean,704552.126027,3.445703,760.727071,273.747835,284.533866,121.609260,36.384299,7.741395,44.125805,161.281058,4.100489,16.091939,64.588830,41.192205,39.726849,64.922607,17.524983,0.189984,5.148235,3.220853,2.432823,3.526760,2.906618,6.434488,47.515101,8.610557,4.544180,1.762714,1.711415,84.513547,76.090606,8.422940,13.888852
std,9589.945480,5.638715,614.408240,226.395986,236.603047,110.472516,41.152105,13.968684,51.554751,135.006546,4.326103,13.543169,43.875234,31.277963,29.950031,44.717338,15.169477,0.512794,5.410963,3.940306,2.669649,3.232522,3.547386,5.932780,38.868007,5.258440,3.306925,0.700117,0.815247,10.880676,11.967419,14.989169,10.134464
min,631965.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,1.000000,1.000000,59.000000,51.000000,-36.000000,1.000000
25%,699546.000000,0.000000,261.250000,116.000000,76.000000,25.000000,0.000000,0.000000,0.000000,34.000000,0.000000,4.000000,36.000000,17.000000,18.000000,36.000000,4.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,20.000000,4.000000,2.000000,1.000000,1.000000,76.000000,67.000000,-1.000000,6.000000
50%,703456.000000,1.000000,762.000000,257.000000,290.000000,115.000000,26.000000,0.000000,30.000000,151.000000,3.000000,16.000000,62.000000,40.000000,38.000000,63.000000,17.000000,0.000000,4.000000,2.000000,2.000000,3.000000,2.000000,6.000000,48.000000,8.000000,3.000000,2.000000,1.000000,85.000000,75.000000,8.000000,11.000000
75%,713017.000000,5.000000,1118.000000,383.000000,431.000000,183.000000,55.000000,11.000000,67.000000,248.000000,6.000000,24.000000,86.000000,59.000000,55.000000,87.000000,27.000000,0.000000,7.000000,4.000000,4.000000,5.000000,5.000000,10.000000,68.000000,13.000000,6.000000,2.000000,2.000000,92.000000,83.000000,19.000000,20.000000
max,721629.000000,93.000000,8154.000000,3217.000000,2811.000000,1560.000000,684.000000,147.000000,794.000000,781.000000,63.000000,164.000000,594.000000,457.000000,435.000000,608.000000,187.000000,6.000000,82.000000,53.000000,42.000000,39.000000,51.000000,75.000000,497.000000,19.000000,18.000000,3.000000,3.000000,112.000000,112.000000,51.000000,51.000000

In [8]:
dados['interv_dias'].isnull().sum() # esses dados nan existem memso ou sao erros de importação

np.int64(88)

## Filtro inicial:

- selecionando apenas os jogos dos anos 2022, 2023 e 2024
- retirando os quartos 5 e 6 porque sao prorrogações e o jogo completo tbm saiu

In [9]:
dados['temp'].unique()

array(['20/21', '24/25', '21/22', '23/24', '22/23'], dtype=object)

In [10]:
# subistituindo / por _ na coluna temp
dados['temp'] = dados['temp'].str.replace('/', '_')

In [11]:
dados['temp'].unique()

array(['20_21', '24_25', '21_22', '23_24', '22_23'], dtype=object)

In [12]:
# filtrando os dados da coluna temp
dados = dados[dados['temp'].isin(['22_23', '23_24', '24_25'])].copy()

In [13]:
# Retirando os quartos 5 e 6 e jogo completo da coluna quarto_jg
dados = dados[dados['quarto_jg'].isin(['1º Quarto', '2º Quarto', '3º Quarto', '4º Quarto'])].copy()

In [14]:
dados['quarto_jg'].unique()

array(['1º Quarto', '2º Quarto', '3º Quarto', '4º Quarto'], dtype=object)

#Analise exploratória

In [15]:
# Retirar informações desnecessarias da tabela
# Diferenciar duas tabelas

## Contrução da base dados bruta

In [55]:
dados_brutos = dados[['npf', 'nome_sessao', 'quarto_jg', 'vel_max', 'sprints', 'zv1', 'zv2', 'zv3', 'zv4', 'zv5', 'dcel1', 'dcel2', 'dcel3', 'dcel4', 'acel1', 'acel2', 'acel3', 'acel4', 'fc1', 'fc2', 'fc3', 'fc4', 'fc5', 'fc_80', 'trimp', 'dai', 'dmi', 'adversario', 'idade', 'classificacao', 'interv_dias', 'mando', 'posicao', 'dif', 'tempo', 'temp']].copy()

In [56]:
dados_brutos.head()

,npf,nome_sessao,quarto_jg,vel_max,sprints,zv1,zv2,zv3,zv4,zv5,dcel1,dcel2,dcel3,dcel4,acel1,acel2,acel3,acel4,fc1,fc2,fc3,fc4,fc5,fc_80,trimp,dai,dmi,adversario,idade,classificacao,interv_dias,mando,posicao,dif,tempo,temp
2638,703222,22.10.15_Flamengo,1º Quarto,"9,3",0,35,6,0,0,0,7,22,0,0,8,21,0,0,8,1,0,0,0,0,11,0,0.0,Flamengo,"20,00",3.0,NaN,2,3,-12,"0,0",22_23
2639,709501,22.10.15_Flamengo,1º Quarto,"7,1",0,88,4,0,0,0,8,50,3,0,11,54,0,0,5,0,0,0,0,0,5,0,0.0,Flamengo,"19,00",3.0,NaN,2,1,-12,"0,0",22_23
2640,703222,22.10.15_Flamengo,2º Quarto,"6,9",0,86,2,0,0,0,19,41,1,0,27,35,0,0,6,1,0,0,0,0,11,0,0.0,Flamengo,"20,00",3.0,NaN,2,3,-12,"0,0",22_23
2641,709501,22.10.15_Flamengo,2º Quarto,"7,3",0,98,8,0,0,0,14,60,2,0,18,61,0,0,1,0,0,0,0,0,1,0,0.0,Flamengo,"19,00",3.0,NaN,2,1,-12,"0,0",22_23
2642,703222,22.10.15_Flamengo,3º Quarto,"6,5",0,51,1,0,0,0,16,28,1,0,16,29,0,0,5,1,0,0,0,0,8,0,0.0,Flamengo,"20,00",3.0,NaN,2,3,-12,"0,0",22_23

In [57]:
dados_brutos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6191 entries, 2638 to 9005
Data columns (total 36 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   npf            6191 non-null   int64
 1   nome_sessao    6191 non-null   object
 2   quarto_jg      6191 non-null   object
 3   vel_max        6191 non-null   object
 4   sprints        6191 non-null   int64
 5   zv1            6191 non-null   int64
 6   zv2            6191 non-null   int64
 7   zv3            6191 non-null   int64
 8   zv4            6191 non-null   int64
 9   zv5            6191 non-null   int64
 10  dcel1          6191 non-null   int64
 11  dcel2          6191 non-null   int64
 12  dcel3          6191 non-null   int64
 13  dcel4          6191 non-null   int64
 14  acel1          6191 non-null   int64
 15  acel2          6191 non-null   int64
 16  acel3          6191 non-null   int64
 17  acel4          6191 non-null   int64
 18  fc1            6191 non-null   int64
 19  fc2            6191 non-null   int64
 20  fc3            6191 non-null   int64
 21  fc4            6191 non-null   int64
 22  fc5            6191 non-null   int64
 23  fc_80          6191 non-null   int64
 24  trimp          6191 non-null   int64
 25  dai            6191 non-null   int64
 26  dmi            6191 non-null   float64
 27  adversario     6191 non-null   object
 28  idade          6191 non-null   object
 29  classificacao  6191 non-null   float64
 30  interv_dias    6103 non-null   float64
 31  mando          6191 non-null   int64
 32  posicao        6191 non-null   int64
 33  dif            6191 non-null   int64
 34  tempo          6185 non-null   object
 35  temp           6191 non-null   object
dtypes: float64(3), int64(26), object(7)
memory usage: 1.7+ MB

In [58]:
existe_string = dados_brutos.map(lambda x: isinstance(x, str)).any().any()
print(existe_string)

True

## A base de dados possui incoerencia do tipo:

- mistura de tipos de dados em uma mesma coluna
- inconsistências de registro

In [59]:
# colunas com dados tipo str()

# mascara booleana novamente
mascara_string = dados_brutos.map(lambda x: isinstance(x, str))

# quais colunas possuem ao menos uma string
colunas_com_string = mascara_string.any()
colunas_alvo = colunas_com_string[colunas_com_string].index.tolist()

print(f"Colunas com strings detectadas: {colunas_alvo}")

# Para cada coluna detectada, mostramos os valores únicos que são strings
for col in colunas_alvo:
    # Filtramos apenas as células que são strings naquela coluna específica
    valores_encontrados = dados_brutos.loc[mascara_string[col], col].unique()
    print(f"-> Na coluna '{col}', encontramos: {valores_encontrados}\n")

Colunas com strings detectadas: ['nome_sessao', 'quarto_jg', 'vel_max', 'adversario', 'idade', 'tempo', 'temp']
-> Na coluna 'nome_sessao', encontramos: ['22.10.15_Flamengo' '22.10.18_Pinheiros' '22.10.20_Bauru'
 '22.10.24_Franca' '22.10.28_Caxias' '22.11.05_União Corinthians'
 '22.11.17_Cerrado' '22.11.19_Brasilia' '22.11.23_São José'
 '22.11.29_Fortaleza' '22.12.03_Paulistano' '22.12.08_Rio Claro'
 '22.12.19_Corinthians' '22.12.21_Pato' '22.12.27_São Paulo'
 '23.01.06_Unifacisa' '23.01.10_Bauru' '23.01.12_Pinheiros'
 '23.01.30_São José' '23.02.10_Caxias' '23.02.12_União Corinthians'
 '23.02.15_Cerrado' '23.02.17_Brasilia' '23.03.01_Flamengo'
 '23.03.14_São Paulo' '23.03.21_Franca' '23.03.23_Rio Claro'
 '23.03.28_Corinthians' '23.03.31_Pato' '23.04.03_Paulistano'
 '23.04.06_Unifacisa' '23.04.08_Fortaleza' '23.04.27_Paulistano'
 '23.04.30_Paulistano' '23.05.02_Paulistano' '23.05.07_Paulistano'
 '23.05.09_Paulistano' '23.05.13_Franca' '23.05.16_Franca'
 '23.05.18_Franca' '23.05.21_Franca' '23.05.23_Franca' '23.10.13_Flamengo'
 '23.10.21_Botafogo' '23.10.23_Vasco' '23.11.08_São José' '23.11.10_Mogi'
 '23.11.16_Bauru' '23.11.18_Franca' '23.11.23_São Paulo'
 '23.11.25_Paulistano' '23.11.29_Unifacisa' '23.12.01_Fortaleza'
 '23.12.06_Cerrado' '23.12.14_Corinthians' '23.12.16_Pinheiros'
 '23.12.20_Brasilia' '23.12.22_Pato' '23.12.27_Caxias do Sul'
 '23.12.29_União Corinthians' '24.01.08_Botafogo' '24.01.11_Flamengo'
 '24.01.13_Vasco' '24.01.17_Brasilia' '24.01.19_Cerrado' '24.02.08_Mogi'
 '24.02.15_São Paulo' '24.02.29_Franca' '24.03.02_Bauru'
 '24.03.11_Paulistano' '24.03.20_Fortaleza' '24.03.22_Unifacisa'
 '24.03.25_São José' '24.03.27_Pinheiros' '24.03.30_Corinthians'
 '24.04.05_Pato' '24.04.10_Caxias' '24.04.12_União Corinthians'
 '24.04.19_União Corinthians' '24.04.23_União Corinthians'
 '24.05.03_São Paulo' '24.05.06_São Paulo' '24.05.08_São Paulo'
 '24.05.11_São Paulo' '24.05.13_São Paulo' '24.05.17_Franca'
 '24.05.20_Franca' '24.05.22_Franca' '24.05.25_Franca' '24.05.27_Franca'
 '24.10.12_Brasilia' '24.10.15_Franca' '24.10.17_Bauru'
 '24.10.21_São José' '24.10.24_Mogi' '24.10.29_Pinheiros'
 '24.10.31_Corinthians' '24.11.07_Fortaleza' '24.11.11_Unifacisa'
 '24.11.14_UniaoCor.' '24.11.16_Caxias' '24.11.30_Flamengo'
 '24.12.02_Botafogo' '24.12.05_Pato' '24.12.09_Vasco'
 '24.12.20_Paulistano' '24.12.23_São Paulo' '24.12.27_Bauru'
 '24.12.29_Franca' '25.01.20_São José' '25.01.22_Mogi'
 '25.02.13_Corinthians' '25.02.15_Pinheiros' '25.02.28_Fortaleza'
 '25.03.03_Unifacisa' '25.03.19_Flamengo' '25.03.26_Caxias'
 '25.03.29_União Corinthians' '25.04.01_Brasilia' '25.04.03_Pato'
 '25.04.07_Vasco' '25.04.09_Botafogo' '25.04.12_São Paulo'
 '25.04.14_Paulistano' '25.04.26_Mogi' '25.04.29_Mogi' '25.05.01_Mogi'
 '25.05.09_Vasco' '25.05.12_Vasco' '25.05.14_Vasco' '25.05.23_Bauru'
 '25.05.26_Bauru' '25.05.28_Bauru' '25.06.07_Franca' '25.06.12_Franca'
 '25.06.14_Franca' '25.06.18_Franca']

-> Na coluna 'quarto_jg', encontramos: ['1º Quarto' '2º Quarto' '3º Quarto' '4º Quarto']

-> Na coluna 'vel_max', encontramos: ['9,3' '7,1' '6,9' '7,3' '6,5' '5,2' '8,7' '7,4' '7' '26,9' '27' '26,7'
 '25,6' '27,9' '25,1' '26,8' '23,9' '25,9' '26,3' '25,5' '25,7' '25,8'
 '26' '23,2' '26,2' '26,6' '23,3' '24,6' '22,3' '21,8' '21,5' '24,4'
 '21,7' '20,5' '19,8' '15,9' '5,1' '6' '10,4' '6,7' '12,2' '5' '6,8' '4,6'
 '8,1' '20,8' '26,5' '23,1' '24,3' '21' '21,6' '28,9' '29,6' '24,7' '22,8'
 '27,4' '26,1' '26,4' '27,5' '27,1' '27,8' '11,8' '8,9' '7,8' '5,6' '7,5'
 '7,2' '12,3' '24' '22,2' '22,6' '21,2' '23' '28,6' '28,2' '20,3' '23,8'
 '5,5' '5,8' '7,7' '6,4' '5,4' '11' '6,1' '10,8' '20,4' '20,6' '24,1' '19'
 '29,4' '21,9' '19,2' '23,7' '22,5' '25,3' '6,2' '6,3' '5,3' '10,5' '15,1'
 '10,9' '18,3' '4,2' '21,1' '25,2' '28,1' '23,4' '30,3' '10,2' '7,6'
 '10,6' '17,5' '24,2' '31,1' '27,2' '23,6' '20,1' '22,7' '6,6' '11,3' '0'
 '19,1' '21,3' '31,2' '27,3' '13,1' '17,3' '19,5' '20' '24,5' '29' '27,6'
 '9,5' '7,9' '11,9' '24,9' '23,5' '22,9' '29,8' '30,9' '20,2' '29,5'
 '29,2' '10,1' '5,7' '8,4' '13,3' '11,5' '16' '25,4' '14,4' '9,2' '33,4'
 '18' '16,5' '20,7' '18,2' '29,3' '22,1' '20,9' '21,4' '9,8' '4,8' '4,9'
 '28,5' '22' '29,7' '8,8' '8' '11,2' '24,8' '22,4' '25' '8,6' '5,9' '9'
 '18,5' '18,1' '19,4' '19,9' '8,3' '8,2' '18,6' '4,1' '18,8' '17,8' '11,6'
 '11,7' '19,7' '19,6' '3,9' '9,7' '27,7' '28,3' '12' '2,2' '14,9' '18,4'
 '9,1' '10,3' '13,6' '28,7' '28,4' '10' '29,9' '12,7' '14,8' '17,4' '18,7'
 '14,1' '18,9' '30,1' '17,9' '13,7' '15,3' '13,5' '4,5' '17,7' '16,1' '28'
 '19,3' '15,6' '14,3' '14' '10,7' '15,5' '9,9' '16,4' '17' '4,3' '8,5'
 '13,8' '11,1' '13,2' '11,4' '17,1' '9,4' '12,1' '16,2' '16,7' '14,6'
 '14,5' '15,7' '17,6' '13' '16,8' '4,7' '16,9' '28,8' '29,1' '15,4' '4,4'
 '12,6' '15,8' '15,2' '9,6' '14,7' '12,9' '12,8' '17,2' '12,4' '31,3' '34'
 '32' '13,9' '13,4' '16,3' '4' '16,6' '3,7' '30,6' '33' '3,6' '2,3' '30,7'
 '3,8' '30,5' '30,4' '15' '31' '14,2']

-> Na coluna 'adversario', encontramos: ['Flamengo' 'Pinheiros' 'Bauru' 'Franca' 'Caxias' 'União Corinthians'
 'Cerrado' 'Brasilia' 'São José' 'Fortaleza' 'Paulistano' 'Rio Claro'
 'Corinthians' 'Pato' 'São Paulo' 'Unifacisa' 'Botafogo' 'Vasco' 'Mogi']

-> Na coluna 'idade', encontramos: ['20,00' '19,00' '28,00' '27,00' '30,00' '33,00' '32,00' '25,00' '26,00'
 '31,00' '21,00' '34,00' '29,00' '18,00' '24,00' '35,00' '16,00' '22,00'
 '17,00' '36,00' '37,00']

-> Na coluna 'tempo', encontramos: ['0,0' '4,9' '3,1' '10,0' '1,9' '4,4' '6,5' '7,0' '2,4' '5,9' '0,6' '6,2'
 '7,6' '0,9' '9,4' '7,1' '5,6' '2,6' '7,4' '4,0' '6,0' '7,2' '6,4' '8,3'
 '3,6' '3,8' '3,7' '2,2' '3,0' '3,2' '3,5' '4,1' '4,6' '4,7' '5,0' '5,1'
 '6,6' '6,8' '7,5' '7,8' '7,9' '8,4' '8,9' '9,2' '9,3' '1,8' '2,5' '3,4'
 '5,2' '6,1' '6,3' '7,3' '9,7' '1,4' '1,5' '5,8' '6,9' '8,1' '8,5' '8,6'
 '9,5' '1,1' '2,1' '3,3' '4,2' '5,4' '5,5' '5,7' '6,7' '1,6' '1,7' '2,0'
 '4,3' '8,0' '9,9' '0,8' '2,8' '0,3' '2,3' '2,9' '5,3' '7,7' '4,5' '4,8'
 '0,2' '0,4' '1,3' '8,7' '9,1' '9,6' '9,8' '1,2' '8,8' '3,9' '1,0' '9,0'
 '0,1' '2,7' '0,5' '0,7' '8,2' '0' '3' '1' '8' '10' '7' '6' '4' '5' '2'
 '9']

-> Na coluna 'temp', encontramos: ['22_23' '23_24' '24_25']

##Tratamento por coluna com inconsistências

### **quarto_jg**

transfomações:

Jogo completo = 0

1º Quarto = 1

2º Quarto = 2

3º Quarto = 3

4º Quarto = 4

5º Quarto = 5  

6º Quarto = 6

In [60]:
mapa_quartos_jogo = {
    'Jogo completo': 0,
    '1º Quarto': 1,
    '2º Quarto': 2,
    '3º Quarto': 3,
    '4º Quarto': 4,
    '5º Quarto': 5,
    '6º Quarto': 6
}

dados_brutos['quarto_jg'] = dados_brutos['quarto_jg'].map(mapa_quartos_jogo)

dados_brutos['quarto_jg'].info()
#Na proxima etapa da analise é necessario transformar esse dado em fator

<class 'pandas.core.series.Series'>
Index: 6191 entries, 2638 to 9005
Series name: quarto_jg
Non-Null Count  Dtype
--------------  -----
6191 non-null   int64
dtypes: int64(1)
memory usage: 96.7 KB

In [61]:
dados_brutos['quarto_jg'].unique()

array([1, 2, 3, 4])

### **vel_max**

Transformações:

- substituição de vírgula por ponto

In [62]:
dados_brutos['vel_max'] = dados_brutos['vel_max'].str.replace(',', '.')

In [63]:
#transformando a coluna vel_max em float()
dados_brutos['vel_max'] = dados_brutos['vel_max'].astype(float)

### **adversario**

Transformações:

'Flamengo' = 'flameng'

'Pato' = 'pato'

'Campo Mourão' = 'camp_mour'

'Fortaleza' = 'fortalez'

'Unifacisa' = 'unifac'

'Bauru' = 'bauru'

'Brasilia' = 'brasil'

'Caxias do Sul' = 'caxias_sul'

'Cerrado' = 'cerr'

'Mogi' = 'mogi'

'São Paulo' = 'sp'

'Pinheiros' = 'pinheir'

'Franca' = 'franc'

'Paulistano' = 'paulist'

'Corinthians' = 'corint'

' Franca' = 'franc'

'Rio Claro' = 'rio_cl'

'União Corinthians' = 'uniao_corint'

'Caxias' = 'caxias'

'São José' = 'sao_jos'

'Botafogo' = 'botaf'

'Vasco' = 'vasc'

In [64]:
mapa_adversario = {
'Flamengo' : 'flameng',
'Pato' : 'pato',
'Campo Mourão' : 'camp_mour',
'Fortaleza' : 'fortalez',
'Unifacisa' : 'unifac',
'Bauru' : 'bauru',
'Brasilia' : 'brasil',
'Caxias do Sul' : 'caxias_sul',
'Cerrado' : 'cerr',
'Mogi' : 'mogi',
'São Paulo' : 'sp',
'Pinheiros' : 'pinheir',
'Franca' : 'franc',
'Paulistano' : 'paulist',
'Corinthians' : 'corint',
' Franca' : 'franc',
'Rio Claro' : 'rio_cl',
'União Corinthians' : 'uniao_corint',
'Caxias' : 'caxias',
'São José' : 'sao_jos',
'Botafogo' : 'botaf',
'Vasco' : 'vasc'}

In [65]:
dados_brutos['adversario'] = dados_brutos['adversario'].map(mapa_adversario)

In [66]:
dados_brutos['adversario'].unique()

array(['flameng', 'pinheir', 'bauru', 'franc', 'caxias', 'uniao_corint',
       'cerr', 'brasil', 'sao_jos', 'fortalez', 'paulist', 'rio_cl',
       'corint', 'pato', 'sp', 'unifac', 'botaf', 'vasc', 'mogi'],
      dtype=object)

### **idade**

transformações:

- para dados do tipo int()

In [67]:
dados_brutos['idade'] = dados_brutos['idade'].str.replace(',', '.')

In [68]:
dados_brutos['idade'] = dados_brutos['idade'].astype(float).round().astype(int)

In [69]:
dados_brutos['idade'].unique()

array([20, 19, 28, 27, 30, 33, 32, 25, 26, 31, 21, 34, 29, 18, 24, 35, 16,
       22, 17, 36, 37])

### **tempo**

tranformações:

- trocar vírgula por ponto
- retirando informações **nan**

In [70]:
dados_brutos['tempo'] = dados_brutos['tempo'].str.replace(',', '.')

In [71]:
dados_brutos['tempo'].describe()

count     6185
unique     112
top          0
freq       907
Name: tempo, dtype: object

In [72]:
dados_brutos['tempo'].unique()

array(['0.0', '4.9', '3.1', '10.0', '1.9', '4.4', '6.5', '7.0', '2.4',
       '5.9', '0.6', '6.2', '7.6', '0.9', '9.4', '7.1', '5.6', '2.6',
       '7.4', '4.0', '6.0', '7.2', '6.4', '8.3', '3.6', '3.8', '3.7',
       '2.2', '3.0', '3.2', '3.5', '4.1', '4.6', '4.7', '5.0', '5.1',
       '6.6', '6.8', '7.5', '7.8', '7.9', '8.4', '8.9', '9.2', '9.3',
       '1.8', '2.5', '3.4', '5.2', '6.1', '6.3', '7.3', '9.7', '1.4',
       '1.5', '5.8', '6.9', '8.1', '8.5', '8.6', '9.5', '1.1', '2.1',
       '3.3', '4.2', '5.4', '5.5', '5.7', '6.7', '1.6', '1.7', '2.0',
       '4.3', '8.0', '9.9', '0.8', '2.8', '0.3', '2.3', '2.9', '5.3',
       '7.7', '4.5', '4.8', '0.2', '0.4', '1.3', '8.7', '9.1', '9.6',
       '9.8', '1.2', '8.8', '3.9', '1.0', '9.0', '0.1', '2.7', '0.5',
       '0.7', '8.2', '0', '3', '1', '8', '10', '7', '6', '4', '5', '2',
       '9', nan], dtype=object)

In [73]:
dados_brutos['tempo'].isnull().sum()

np.int64(6)

In [74]:
#tranformando a coluna dados no tipo float()
dados_brutos['tempo'] = dados_brutos['tempo'].astype(float)

### **mando, posição, interv_dias, classificação, idade, dif, nome_sessao**

- Verificação dessas colunas em especial

In [75]:
# tipo de dados da coluna mando
# mando tem dois niveis: 1 = fora e 2 = casa
dados_brutos['mando'].info()

<class 'pandas.core.series.Series'>
Index: 6191 entries, 2638 to 9005
Series name: mando
Non-Null Count  Dtype
--------------  -----
6191 non-null   int64
dtypes: int64(1)
memory usage: 96.7 KB

In [76]:
dados_brutos['mando'].isnull().sum()

np.int64(0)

In [77]:
# tipo de dado da coluna posição
# a posição foi classificado nos niveis: 3 = armadores, 2 = pivos e 1 = alas
dados_brutos['posicao'].unique()

array([3, 1, 2])

In [78]:
# tipo de dado da coluna interv_dia
dados_brutos['interv_dias'].isnull().sum() #??????

np.int64(88)

In [79]:
# tipo de dado da coluna classificação
dados_brutos['classificacao'].info() # o tipo de dado de classificação tem que ser inteiro int(64)

<class 'pandas.core.series.Series'>
Index: 6191 entries, 2638 to 9005
Series name: classificacao
Non-Null Count  Dtype
--------------  -----
6191 non-null   float64
dtypes: float64(1)
memory usage: 96.7 KB

In [80]:
# modificando o tipo de dado da coluna classificação
dados_brutos['classificacao'] = dados_brutos['classificacao'].astype(int)
dados_brutos['classificacao'].info()

<class 'pandas.core.series.Series'>
Index: 6191 entries, 2638 to 9005
Series name: classificacao
Non-Null Count  Dtype
--------------  -----
6191 non-null   int64
dtypes: int64(1)
memory usage: 96.7 KB

In [81]:
dados_brutos['classificacao'].describe().round(2) # a classificação vai de 1 a 19 memso?

count    6191.00
mean        8.67
std         5.43
min         1.00
25%         4.00
50%         8.00
75%        14.00
max        19.00
Name: classificacao, dtype: float64

In [82]:
# tipo de dado da coluna idade
dados_brutos['idade'].info()

<class 'pandas.core.series.Series'>
Index: 6191 entries, 2638 to 9005
Series name: idade
Non-Null Count  Dtype
--------------  -----
6191 non-null   int64
dtypes: int64(1)
memory usage: 96.7 KB

In [83]:
# tipo de dado da coluna dif
dados_brutos['dif'].describe()

count    6191.000000
mean        8.586497
std        14.706836
min       -31.000000
25%        -1.000000
50%         9.000000
75%        19.000000
max        51.000000
Name: dif, dtype: float64

In [84]:
dados_brutos['dif'].unique()

array([-12,  -9,  10,  -2,   6,  20,  51,   8, -17,  29,  14,   1,   5,
         7,   4,  31,  -1,  11,  -4,  18,   2,  -8,  35, -10,   9,   3,
       -15, -14,  17,  12,  19,  15,  30,  24,  37,  43,  13,  25, -31,
       -24,  -6,  27,  26,  22,  38,  23, -16, -13])

In [85]:
dados_brutos['dif'].info()

<class 'pandas.core.series.Series'>
Index: 6191 entries, 2638 to 9005
Series name: dif
Non-Null Count  Dtype
--------------  -----
6191 non-null   int64
dtypes: int64(1)
memory usage: 96.7 KB

In [86]:
# tipo de dado da coluna nome_sessao
dados_brutos['nome_sessao'].describe()

count                   6191
unique                   137
top       24.11.07_Fortaleza
freq                      52
Name: nome_sessao, dtype: object

### **Segunda verificação de inconsistencias**

In [87]:
# colunas com dados tipo str()

# mascara booleana novamente
mascara_string = dados_brutos.map(lambda x: isinstance(x, str))

# quais colunas possuem ao menos uma string
colunas_com_string = mascara_string.any()
colunas_alvo = colunas_com_string[colunas_com_string].index.tolist()

print(f"Colunas com strings detectadas: {colunas_alvo}")

# Para cada coluna detectada, mostramos os valores únicos que são strings
for col in colunas_alvo:
    # Filtramos apenas as células que são strings naquela coluna específica
    valores_encontrados = dados_brutos.loc[mascara_string[col], col].unique()
    print(f"-> Na coluna '{col}', encontramos: {valores_encontrados}\n")

Colunas com strings detectadas: ['nome_sessao', 'adversario', 'temp']
-> Na coluna 'nome_sessao', encontramos: ['22.10.15_Flamengo' '22.10.18_Pinheiros' '22.10.20_Bauru'
 '22.10.24_Franca' '22.10.28_Caxias' '22.11.05_União Corinthians'
 '22.11.17_Cerrado' '22.11.19_Brasilia' '22.11.23_São José'
 '22.11.29_Fortaleza' '22.12.03_Paulistano' '22.12.08_Rio Claro'
 '22.12.19_Corinthians' '22.12.21_Pato' '22.12.27_São Paulo'
 '23.01.06_Unifacisa' '23.01.10_Bauru' '23.01.12_Pinheiros'
 '23.01.30_São José' '23.02.10_Caxias' '23.02.12_União Corinthians'
 '23.02.15_Cerrado' '23.02.17_Brasilia' '23.03.01_Flamengo'
 '23.03.14_São Paulo' '23.03.21_Franca' '23.03.23_Rio Claro'
 '23.03.28_Corinthians' '23.03.31_Pato' '23.04.03_Paulistano'
 '23.04.06_Unifacisa' '23.04.08_Fortaleza' '23.04.27_Paulistano'
 '23.04.30_Paulistano' '23.05.02_Paulistano' '23.05.07_Paulistano'
 '23.05.09_Paulistano' '23.05.13_Franca' '23.05.16_Franca'
 '23.05.18_Franca' '23.05.21_Franca' '23.05.23_Franca' '23.10.13_Flamengo'
 '23.10.21_Botafogo' '23.10.23_Vasco' '23.11.08_São José' '23.11.10_Mogi'
 '23.11.16_Bauru' '23.11.18_Franca' '23.11.23_São Paulo'
 '23.11.25_Paulistano' '23.11.29_Unifacisa' '23.12.01_Fortaleza'
 '23.12.06_Cerrado' '23.12.14_Corinthians' '23.12.16_Pinheiros'
 '23.12.20_Brasilia' '23.12.22_Pato' '23.12.27_Caxias do Sul'
 '23.12.29_União Corinthians' '24.01.08_Botafogo' '24.01.11_Flamengo'
 '24.01.13_Vasco' '24.01.17_Brasilia' '24.01.19_Cerrado' '24.02.08_Mogi'
 '24.02.15_São Paulo' '24.02.29_Franca' '24.03.02_Bauru'
 '24.03.11_Paulistano' '24.03.20_Fortaleza' '24.03.22_Unifacisa'
 '24.03.25_São José' '24.03.27_Pinheiros' '24.03.30_Corinthians'
 '24.04.05_Pato' '24.04.10_Caxias' '24.04.12_União Corinthians'
 '24.04.19_União Corinthians' '24.04.23_União Corinthians'
 '24.05.03_São Paulo' '24.05.06_São Paulo' '24.05.08_São Paulo'
 '24.05.11_São Paulo' '24.05.13_São Paulo' '24.05.17_Franca'
 '24.05.20_Franca' '24.05.22_Franca' '24.05.25_Franca' '24.05.27_Franca'
 '24.10.12_Brasilia' '24.10.15_Franca' '24.10.17_Bauru'
 '24.10.21_São José' '24.10.24_Mogi' '24.10.29_Pinheiros'
 '24.10.31_Corinthians' '24.11.07_Fortaleza' '24.11.11_Unifacisa'
 '24.11.14_UniaoCor.' '24.11.16_Caxias' '24.11.30_Flamengo'
 '24.12.02_Botafogo' '24.12.05_Pato' '24.12.09_Vasco'
 '24.12.20_Paulistano' '24.12.23_São Paulo' '24.12.27_Bauru'
 '24.12.29_Franca' '25.01.20_São José' '25.01.22_Mogi'
 '25.02.13_Corinthians' '25.02.15_Pinheiros' '25.02.28_Fortaleza'
 '25.03.03_Unifacisa' '25.03.19_Flamengo' '25.03.26_Caxias'
 '25.03.29_União Corinthians' '25.04.01_Brasilia' '25.04.03_Pato'
 '25.04.07_Vasco' '25.04.09_Botafogo' '25.04.12_São Paulo'
 '25.04.14_Paulistano' '25.04.26_Mogi' '25.04.29_Mogi' '25.05.01_Mogi'
 '25.05.09_Vasco' '25.05.12_Vasco' '25.05.14_Vasco' '25.05.23_Bauru'
 '25.05.26_Bauru' '25.05.28_Bauru' '25.06.07_Franca' '25.06.12_Franca'
 '25.06.14_Franca' '25.06.18_Franca']

-> Na coluna 'adversario', encontramos: ['flameng' 'pinheir' 'bauru' 'franc' 'caxias' 'uniao_corint' 'cerr'
 'brasil' 'sao_jos' 'fortalez' 'paulist' 'rio_cl' 'corint' 'pato' 'sp'
 'unifac' 'botaf' 'vasc' 'mogi']

-> Na coluna 'temp', encontramos: ['22_23' '23_24' '24_25']

In [88]:
# Encontrando valores 0 na coluna tempo
tabela_tempo_0 = dados_brutos[dados_brutos['tempo'] == 0]

In [89]:
tabela_tempo_0.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1396 entries, 2638 to 8973
Data columns (total 36 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   npf            1396 non-null   int64
 1   nome_sessao    1396 non-null   object
 2   quarto_jg      1396 non-null   int64
 3   vel_max        1396 non-null   float64
 4   sprints        1396 non-null   int64
 5   zv1            1396 non-null   int64
 6   zv2            1396 non-null   int64
 7   zv3            1396 non-null   int64
 8   zv4            1396 non-null   int64
 9   zv5            1396 non-null   int64
 10  dcel1          1396 non-null   int64
 11  dcel2          1396 non-null   int64
 12  dcel3          1396 non-null   int64
 13  dcel4          1396 non-null   int64
 14  acel1          1396 non-null   int64
 15  acel2          1396 non-null   int64
 16  acel3          1396 non-null   int64
 17  acel4          1396 non-null   int64
 18  fc1            1396 non-null   int64
 19  fc2            1396 non-null   int64
 20  fc3            1396 non-null   int64
 21  fc4            1396 non-null   int64
 22  fc5            1396 non-null   int64
 23  fc_80          1396 non-null   int64
 24  trimp          1396 non-null   int64
 25  dai            1396 non-null   int64
 26  dmi            1396 non-null   float64
 27  adversario     1396 non-null   object
 28  idade          1396 non-null   int64
 29  classificacao  1396 non-null   int64
 30  interv_dias    1379 non-null   float64
 31  mando          1396 non-null   int64
 32  posicao        1396 non-null   int64
 33  dif            1396 non-null   int64
 34  tempo          1396 non-null   float64
 35  temp           1396 non-null   object
dtypes: float64(4), int64(29), object(3)
memory usage: 403.5+ KB

O que deve ser feito quando o tempo == 0 no data set?

eu retirei todas

In [90]:
dados_brutos = dados_brutos[dados_brutos['tempo'] > 1].copy()

In [91]:
#exportando base de dados brutos tratados
dados_brutos.to_csv('base_dados_brutos_tratados.csv', index=False)

## Contrução da base de dados derivada

In [92]:
df = pd.DataFrame()

In [93]:
df['npf'] = dados_brutos['npf']
df['quarto_jg'] = dados_brutos['quarto_jg']
df['vel_max'] = dados_brutos['vel_max']
df['adversario'] = dados_brutos['adversario']
df['idade'] = dados_brutos['idade']
df['classificacao'] = dados_brutos['classificacao']
df['interv_dias'] = dados_brutos['interv_dias']
df['mando'] = dados_brutos['mando']
df['posicao'] = dados_brutos['posicao']
df['idade'] = dados_brutos['idade']
df['dif'] = dados_brutos['dif']
df['nome_sessao'] = dados_brutos['nome_sessao']
df['tempo'] = dados_brutos['tempo']
df['sprints'] = dados_brutos['sprints']/ dados_brutos['tempo']
df['zv1_minn'] = dados_brutos['zv1']/ dados_brutos['tempo']
df['zv2_minn'] = dados_brutos['zv2']/ dados_brutos['tempo']
df['zv3_minn'] = dados_brutos['zv3']/ dados_brutos['tempo']
df['zv4_minn'] = dados_brutos['zv4']/ dados_brutos['tempo']
df['zv5_minn'] = dados_brutos['zv5']/ dados_brutos['tempo']
df['dcel1_minn'] = dados_brutos['dcel1']/ dados_brutos['tempo']
df['dcel2_minn'] = dados_brutos['dcel2']/ dados_brutos['tempo']
df['dcel3_minn'] = dados_brutos['dcel3']/ dados_brutos['tempo']
df['dcel4_minn'] = dados_brutos['dcel4']/ dados_brutos['tempo']
df['acel1_minn'] = dados_brutos['acel1']/ dados_brutos['tempo']
df['acel2_minn'] = dados_brutos['acel2']/ dados_brutos['tempo']
df['acel3_minn'] = dados_brutos['acel3']/ dados_brutos['tempo']
df['acel4_minn'] = dados_brutos['acel4']/ dados_brutos['tempo']
df['fc1_minn'] = dados_brutos['fc1']/ dados_brutos['tempo']
df['fc2_minn'] = dados_brutos['fc2']/ dados_brutos['tempo']
df['fc3_minn'] = dados_brutos['fc3']/ dados_brutos['tempo']
df['fc4_minn'] = dados_brutos['fc4']/ dados_brutos['tempo']
df['fc5_minn'] = dados_brutos['fc5']/ dados_brutos['tempo']
df['fc_80_minn'] = dados_brutos['fc_80']/ dados_brutos['tempo']

df['dai_minn'] = dados_brutos['dai']/ dados_brutos['tempo']
df['dmi_minn'] = dados_brutos['dmi']/ dados_brutos['tempo']
df['trimp_min'] = dados_brutos['trimp']/ dados_brutos['tempo']
df['temp'] = dados_brutos['temp']

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4628 entries, 2647 to 9005
Data columns (total 36 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   npf            4628 non-null   int64
 1   quarto_jg      4628 non-null   int64
 2   vel_max        4628 non-null   float64
 3   adversario     4628 non-null   object
 4   idade          4628 non-null   int64
 5   classificacao  4628 non-null   int64
 6   interv_dias    4561 non-null   float64
 7   mando          4628 non-null   int64
 8   posicao        4628 non-null   int64
 9   dif            4628 non-null   int64
 10  nome_sessao    4628 non-null   object
 11  tempo          4628 non-null   float64
 12  sprints        4628 non-null   float64
 13  zv1_minn       4628 non-null   float64
 14  zv2_minn       4628 non-null   float64
 15  zv3_minn       4628 non-null   float64
 16  zv4_minn       4628 non-null   float64
 17  zv5_minn       4628 non-null   float64
 18  dcel1_minn     4628 non-null   float64
 19  dcel2_minn     4628 non-null   float64
 20  dcel3_minn     4628 non-null   float64
 21  dcel4_minn     4628 non-null   float64
 22  acel1_minn     4628 non-null   float64
 23  acel2_minn     4628 non-null   float64
 24  acel3_minn     4628 non-null   float64
 25  acel4_minn     4628 non-null   float64
 26  fc1_minn       4628 non-null   float64
 27  fc2_minn       4628 non-null   float64
 28  fc3_minn       4628 non-null   float64
 29  fc4_minn       4628 non-null   float64
 30  fc5_minn       4628 non-null   float64
 31  fc_80_minn     4628 non-null   float64
 32  dai_minn       4628 non-null   float64
 33  dmi_minn       4628 non-null   float64
 34  trimp_min      4628 non-null   float64
 35  temp           4628 non-null   object
dtypes: float64(26), int64(7), object(3)
memory usage: 1.3+ MB

In [95]:
df.head()

,npf,quarto_jg,vel_max,adversario,idade,classificacao,interv_dias,mando,posicao,dif,nome_sessao,tempo,sprints,zv1_minn,zv2_minn,zv3_minn,zv4_minn,zv5_minn,dcel1_minn,dcel2_minn,dcel3_minn,dcel4_minn,acel1_minn,acel2_minn,acel3_minn,acel4_minn,fc1_minn,fc2_minn,fc3_minn,fc4_minn,fc5_minn,fc_80_minn,dai_minn,dmi_minn,trimp_min,temp
2647,709286,2,26.9,flameng,28,3,NaN,2,1,-12,22.10.15_Flamengo,4.9,3.265306,75.306122,88.775510,39.591837,27.346939,7.142857,11.428571,16.530612,3.061224,2.653061,10.408163,14.897959,5.714286,0.204082,1.428571,1.224490,0.612245,1.020408,0.612245,1.632653,34.489796,74.081633,12.857143,22_23
2648,703092,3,27.0,flameng,27,3,NaN,2,3,-12,22.10.15_Flamengo,3.1,2.903226,60.322581,80.967742,33.870968,17.741935,11.935484,11.935484,12.580645,4.516129,1.935484,10.322581,14.838710,3.870968,0.000000,4.516129,0.967742,0.645161,0.645161,1.290323,1.935484,29.677419,63.548387,16.451613,22_23
2649,709286,3,26.7,flameng,28,3,NaN,2,1,-12,22.10.15_Flamengo,10.0,3.000000,66.400000,58.000000,41.200000,17.100000,8.900000,6.500000,14.300000,3.900000,2.100000,5.200000,11.800000,6.300000,0.200000,0.200000,0.400000,0.600000,0.700000,0.500000,1.200000,26.000000,67.200000,7.900000,22_23
2650,709202,2,25.6,flameng,20,3,NaN,2,1,-12,22.10.15_Flamengo,1.9,4.210526,66.315789,79.473684,30.000000,22.631579,2.631579,13.157895,23.684211,5.263158,0.526316,12.631579,23.684211,5.789474,0.000000,3.157895,0.526316,0.526316,1.052632,0.000000,1.052632,25.263158,55.263158,9.473684,22_23
2651,709286,4,27.9,flameng,28,3,NaN,2,1,-12,22.10.15_Flamengo,10.0,2.200000,55.500000,61.400000,39.700000,13.000000,10.800000,8.200000,11.300000,4.000000,1.200000,6.500000,11.100000,5.000000,0.100000,0.200000,0.500000,0.500000,0.700000,0.700000,1.400000,23.800000,63.500000,9.200000,22_23

In [96]:
df['quarto_jg'].unique()

array([2, 3, 4, 1])

In [97]:
#exportar base de dados df
df.to_csv('base_dados_derivada_min.csv', index=False)

### Análise gráfica

In [98]:
# verificar a correlação da cada dado
# quais dados sao esperados a alta corrrelação?

In [99]:
#Saparar as variaveis dependes

# Modelos