#Importando Bibliotecas

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Configuração
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Importando base de dados

In [ ]:
dados = pd.read_csv('/content/(2026) BAS_base_dados - TABELA FILTRADA.csv')

#Analise explanatória

In [ ]:
dados.head()

,npf,data,nome_sessao,quarto_jg,codigo,vel_max,sprints,dits_total,zv1,zv2,zv3,zv4,zv5,dai,dmi,dcel4,dcel3,dcel2,dcel1,acel1,acel2,acel3,acel4,fc1,fc2,fc3,fc4,fc5,fc_80,trimp,tempo,adversario,idade,quarto,classificacao,interv_dias,mando,posicao,temp,placar_mtc,placar_adv,dif,dif_modolo,Competição
0,676677,10/11/2020,20.11.10_Flamengo,1º Quarto,20.11.10_Flamengo1º Quarto676677,"5,9",0.0,83.0,69.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.0,4.0,3.0,29.0,0.0,0.0,17.0,0.0,0.0,0.0,0.0,0.0,17.0,"0,0",Flamengo,"18,00",1,1.0,6.0,3.0,3.0,20/21,68.0,102.0,-34.0,34,NBB
1,676677,10/11/2020,20.11.10_Flamengo,3º Quarto,20.11.10_Flamengo3º Quarto676677,"14,4",0.0,232.0,135.0,54.0,28.0,0.0,0.0,0.0,28.0,0.0,1.0,19.0,13.0,13.0,17.0,2.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,5.0,"0,0",Flamengo,"18,00",3,1.0,6.0,3.0,3.0,20/21,68.0,102.0,-34.0,34,NBB
2,699947,10/11/2020,20.11.10_Flamengo,4º Quarto,20.11.10_Flamengo4º Quarto699947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,0,NaN
3,690318,10/11/2020,20.11.10_Flamengo,3º Quarto,20.11.10_Flamengo3º Quarto690318,"26,1",12.0,1741.0,573.0,620.0,364.0,119.0,14.0,133.0,497.0,4.0,30.0,118.0,79.0,70.0,115.0,33.0,0.0,0.0,1.0,4.0,9.0,9.0,18.0,94.0,"10,0",Flamengo,"18,00",3,1.0,6.0,3.0,3.0,20/21,68.0,102.0,-34.0,34,NBB
4,696806,10/11/2020,20.11.10_Flamengo,2º Quarto,20.11.10_Flamengo2º Quarto696806,"29,3",17.0,2019.0,761.0,655.0,383.0,104.0,27.0,131.0,514.0,15.0,30.0,159.0,107.0,106.0,129.0,49.0,2.0,0.0,1.0,6.0,6.0,16.0,22.0,125.0,"10,0",Flamengo,"28,00",2,1.0,6.0,3.0,1.0,20/21,68.0,102.0,-34.0,34,NBB

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11813 entries, 0 to 11812
Data columns (total 44 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   npf            11813 non-null  int64
 1   data           11813 non-null  object
 2   nome_sessao    11813 non-null  object
 3   quarto_jg      11813 non-null  object
 4   codigo         11813 non-null  object
 5   vel_max        11343 non-null  object
 6   sprints        11343 non-null  float64
 7   dits_total     11343 non-null  float64
 8   zv1            11343 non-null  float64
 9   zv2            11343 non-null  float64
 10  zv3            11343 non-null  float64
 11  zv4            11343 non-null  float64
 12  zv5            11343 non-null  float64
 13  dai            11343 non-null  float64
 14  dmi            11145 non-null  float64
 15  dcel4          11343 non-null  float64
 16  dcel3          11343 non-null  float64
 17  dcel2          11343 non-null  float64
 18  dcel1          11343 non-null  float64
 19  acel1          11343 non-null  float64
 20  acel2          11343 non-null  float64
 21  acel3          11343 non-null  float64
 22  acel4          11343 non-null  float64
 23  fc1            11343 non-null  float64
 24  fc2            11343 non-null  float64
 25  fc3            11343 non-null  float64
 26  fc4            11343 non-null  float64
 27  fc5            11343 non-null  float64
 28  fc_80          11343 non-null  float64
 29  trimp          11343 non-null  float64
 30  tempo          10809 non-null  object
 31  adversario     11343 non-null  object
 32  idade          11343 non-null  object
 33  quarto         11813 non-null  object
 34  classificacao  10746 non-null  float64
 35  interv_dias    11255 non-null  float64
 36  mando          10725 non-null  float64
 37  posicao        11343 non-null  float64
 38  temp           11343 non-null  object
 39  placar_mtc     10623 non-null  float64
 40  placar_adv     10623 non-null  float64
 41  dif            11343 non-null  float64
 42  dif_modolo     11813 non-null  int64
 43  Competição     11343 non-null  object
dtypes: float64(31), int64(2), object(11)
memory usage: 4.0+ MB

In [ ]:
dados.isnull().sum()

npf                 0
data                0
nome_sessao         0
quarto_jg           0
codigo              0
vel_max           470
sprints           470
dits_total        470
zv1               470
zv2               470
zv3               470
zv4               470
zv5               470
dai               470
dmi               668
dcel4             470
dcel3             470
dcel2             470
dcel1             470
acel1             470
acel2             470
acel3             470
acel4             470
fc1               470
fc2               470
fc3               470
fc4               470
fc5               470
fc_80             470
trimp             470
tempo            1004
adversario        470
idade             470
quarto              0
classificacao    1067
interv_dias       558
mando            1088
posicao           470
temp              470
placar_mtc       1190
placar_adv       1190
dif               470
dif_modolo          0
Competição        470
dtype: int64

In [ ]:
dados.describe()

,npf,sprints,dits_total,zv1,zv2,zv3,zv4,zv5,dai,dmi,dcel4,dcel3,dcel2,dcel1,acel1,acel2,acel3,acel4,fc1,fc2,fc3,fc4,fc5,fc_80,trimp,classificacao,interv_dias,mando,posicao,placar_mtc,placar_adv,dif,dif_modolo
count,11813.000000,11343.000000,11343.000000,11343.000000,11343.000000,11343.000000,11343.000000,11343.000000,11343.000000,11145.000000,11343.000000,11343.000000,11343.000000,11343.000000,11343.000000,11343.000000,11343.000000,11343.000000,11343.000000,11343.000000,11343.000000,11343.000000,11343.000000,11343.000000,11343.000000,10746.000000,11255.000000,10725.000000,11343.000000,10623.000000,10623.000000,11343.000000,11813.000000
mean,706823.783459,2.859296,751.762849,270.489906,282.497487,119.230274,35.578771,7.592436,43.171295,158.812831,4.007494,16.018425,63.925681,40.809751,39.408887,64.534250,17.178965,0.185665,5.195715,3.283787,2.431279,3.505157,2.897382,6.402539,47.554792,8.896799,4.556464,1.727086,1.851450,85.616116,77.308858,7.779952,12.032676
std,10590.924720,5.120376,578.972977,213.208605,224.425967,104.348169,39.230101,13.690829,49.393882,130.032506,4.119622,12.872402,41.235286,29.590998,28.226796,42.155037,14.319400,0.502769,5.291349,3.826255,2.538127,3.079380,3.407836,5.652067,36.533252,5.440593,6.285884,0.676798,0.827723,10.739519,12.292724,14.219297,10.366781
min,631965.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,63.000000,51.000000,-36.000000,0.000000
25%,699926.000000,0.000000,309.000000,126.000000,102.000000,34.500000,3.000000,0.000000,3.000000,45.000000,1.000000,6.000000,38.000000,19.000000,20.000000,37.000000,5.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,2.000000,23.000000,4.000000,2.000000,1.000000,1.000000,77.000000,68.000000,0.000000,4.000000
50%,708457.000000,1.000000,757.000000,255.000000,289.000000,114.000000,26.000000,0.000000,30.000000,148.000000,3.000000,16.000000,62.000000,40.000000,38.000000,63.000000,17.000000,0.000000,4.000000,2.000000,2.000000,3.000000,2.000000,6.000000,48.000000,8.000000,3.000000,2.000000,2.000000,86.000000,76.000000,7.000000,10.000000
75%,714226.000000,4.000000,1089.500000,374.000000,421.500000,178.000000,54.000000,11.000000,65.000000,241.000000,6.000000,24.000000,84.000000,58.000000,54.000000,86.000000,26.000000,0.000000,8.000000,4.000000,3.000000,5.000000,5.000000,10.000000,67.000000,14.000000,5.000000,2.000000,3.000000,93.000000,86.000000,17.000000,18.000000
max,724919.000000,93.000000,8154.000000,3217.000000,2811.000000,1560.000000,684.000000,147.000000,794.000000,781.000000,63.000000,164.000000,594.000000,457.000000,435.000000,608.000000,187.000000,6.000000,82.000000,53.000000,42.000000,39.000000,51.000000,75.000000,497.000000,20.000000,102.000000,3.000000,3.000000,112.000000,112.000000,51.000000,51.000000

In [ ]:
dados['interv_dias'].isnull().sum() # esses dados nan existem memso ou sao erros de importação

np.int64(558)

## Filtro inicial:

- selecionando apenas os jogos das temporadas 22_23; 23_24; 26_25; 25_25.
- Mantendo apenas jogos da NBB
- retirando os quartos 5 e 6 porque sao prorrogações e o jogo completo tbm saiu

In [ ]:
dados['temp'].unique()

array(['20/21', nan, '24/25', '21/22', '23/24', '22/23', '25/26'],
      dtype=object)

In [ ]:
# subistituindo / por _ na coluna temp
dados['temp'] = dados['temp'].str.replace('/', '_')

In [ ]:
dados['temp'].unique()

array(['20_21', nan, '24_25', '21_22', '23_24', '22_23', '25_26'],
      dtype=object)

In [ ]:
# filtrando os dados da coluna temp
dados = dados[dados['temp'].isin(['22_23', '23_24', '24_25','25_26'])].copy()

In [ ]:
dados = dados[dados['Competição'].isin(['NBB'])].copy()

In [ ]:
# Retirando os quartos 5 e 6 e jogo completo da coluna quarto_jg
dados = dados[dados['quarto_jg'].isin(['1º Quarto', '2º Quarto', '3º Quarto', '4º Quarto'])].copy()

In [ ]:
dados['quarto_jg'].unique()

array(['1º Quarto', '2º Quarto', '3º Quarto', '4º Quarto'], dtype=object)

#Analise exploratória

In [ ]:
# Retirar informações desnecessarias da tabela
# Diferenciar duas tabelas

## Contrução da base dados bruta

In [ ]:
dados_brutos = dados[['npf', 'nome_sessao', 'quarto_jg', 'vel_max', 'dits_total', 'sprints', 'zv1', 'zv2', 'zv3', 'zv4', 'zv5', 'dcel1', 'dcel2', 'dcel3', 'dcel4', 'acel1', 'acel2', 'acel3', 'acel4', 'fc1', 'fc2', 'fc3', 'fc4', 'fc5', 'fc_80', 'trimp', 'dai', 'dmi', 'adversario', 'idade', 'classificacao', 'interv_dias', 'mando', 'posicao', 'dif', 'tempo', 'temp']].copy()

Criando a zonas de intensidade para aceleração e desaceleração que serão utilizadas nas análises:

*   ac_total: Soma de todas as acelerações que são registradas pelo polar (>0,5 m/s2)
*   acmi (acelerações moderadas a intensas): Soma das acel 2, 3 e 4 (>1 m/s2)
*   aci (acelerações intensas): Soma das acel 3 e 4 (>2 m/s2)

As zonas são as mesmas para as desacelerações

In [ ]:
dados_brutos['ac_total'] = (dados_brutos['acel1']  + dados_brutos['acel2'] + dados_brutos['acel3'] + dados_brutos['acel4'])
dados_brutos['acmi'] = (dados_brutos['acel2'] + dados_brutos['acel3'] + dados_brutos['acel4'])
dados_brutos['aci'] = (dados_brutos['acel3'] + dados_brutos['acel4'])
dados_brutos['dc_total'] = (dados_brutos['dcel1'] + dados_brutos['dcel2'] + dados_brutos['dcel3'] + dados_brutos['dcel4'])
dados_brutos['dci'] = (dados_brutos['dcel3'] + dados_brutos['dcel4'])
dados_brutos['dcmi'] = (dados_brutos['dcel2'] + dados_brutos['dcel3'] + dados_brutos['dcel4'])

In [ ]:
dados_brutos['dif_duo'] = np.where((dados_brutos['dif'] >= 5) | (dados_brutos['dif'] <= -5), 1, 2)

In [ ]:
dados_brutos.head()

,npf,nome_sessao,quarto_jg,vel_max,dits_total,sprints,zv1,zv2,zv3,zv4,zv5,dcel1,dcel2,dcel3,dcel4,acel1,acel2,acel3,acel4,fc1,fc2,fc3,fc4,fc5,fc_80,trimp,dai,dmi,adversario,idade,classificacao,interv_dias,mando,posicao,dif,tempo,temp,ac_total,acmi,aci,dc_total,dci,dcmi,dif_duo
2638,703222,22.10.15_Flamengo,1º Quarto,"9,3",56.0,0.0,35.0,6.0,0.0,0.0,0.0,7.0,22.0,0.0,0.0,8.0,21.0,0.0,0.0,8.0,1.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0,Flamengo,"20,00",3.0,NaN,2.0,3.0,-12.0,"0,0",22_23,29.0,21.0,0.0,29.0,0.0,22.0,1
2639,709501,22.10.15_Flamengo,1º Quarto,"7,1",116.0,0.0,88.0,4.0,0.0,0.0,0.0,8.0,50.0,3.0,0.0,11.0,54.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,Flamengo,"19,00",3.0,NaN,2.0,1.0,-12.0,"0,0",22_23,65.0,54.0,0.0,61.0,3.0,53.0,1
2640,703222,22.10.15_Flamengo,2º Quarto,"6,9",124.0,0.0,86.0,2.0,0.0,0.0,0.0,19.0,41.0,1.0,0.0,27.0,35.0,0.0,0.0,6.0,1.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0,Flamengo,"20,00",3.0,NaN,2.0,3.0,-12.0,"0,0",22_23,62.0,35.0,0.0,61.0,1.0,42.0,1
2641,709501,22.10.15_Flamengo,2º Quarto,"7,3",141.0,0.0,98.0,8.0,0.0,0.0,0.0,14.0,60.0,2.0,0.0,18.0,61.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,Flamengo,"19,00",3.0,NaN,2.0,1.0,-12.0,"0,0",22_23,79.0,61.0,0.0,76.0,2.0,62.0,1
2642,703222,22.10.15_Flamengo,3º Quarto,"6,5",75.0,0.0,51.0,1.0,0.0,0.0,0.0,16.0,28.0,1.0,0.0,16.0,29.0,0.0,0.0,5.0,1.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,Flamengo,"20,00",3.0,NaN,2.0,3.0,-12.0,"0,0",22_23,45.0,29.0,0.0,45.0,1.0,29.0,1

In [ ]:
dados_brutos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8247 entries, 2638 to 11812
Data columns (total 44 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   npf            8247 non-null   int64
 1   nome_sessao    8247 non-null   object
 2   quarto_jg      8247 non-null   object
 3   vel_max        8247 non-null   object
 4   dits_total     8247 non-null   float64
 5   sprints        8247 non-null   float64
 6   zv1            8247 non-null   float64
 7   zv2            8247 non-null   float64
 8   zv3            8247 non-null   float64
 9   zv4            8247 non-null   float64
 10  zv5            8247 non-null   float64
 11  dcel1          8247 non-null   float64
 12  dcel2          8247 non-null   float64
 13  dcel3          8247 non-null   float64
 14  dcel4          8247 non-null   float64
 15  acel1          8247 non-null   float64
 16  acel2          8247 non-null   float64
 17  acel3          8247 non-null   float64
 18  acel4          8247 non-null   float64
 19  fc1            8247 non-null   float64
 20  fc2            8247 non-null   float64
 21  fc3            8247 non-null   float64
 22  fc4            8247 non-null   float64
 23  fc5            8247 non-null   float64
 24  fc_80          8247 non-null   float64
 25  trimp          8247 non-null   float64
 26  dai            8247 non-null   float64
 27  dmi            8247 non-null   float64
 28  adversario     8247 non-null   object
 29  idade          8247 non-null   object
 30  classificacao  8203 non-null   float64
 31  interv_dias    8159 non-null   float64
 32  mando          8247 non-null   float64
 33  posicao        8247 non-null   float64
 34  dif            8247 non-null   float64
 35  tempo          8214 non-null   object
 36  temp           8247 non-null   object
 37  ac_total       8247 non-null   float64
 38  acmi           8247 non-null   float64
 39  aci            8247 non-null   float64
 40  dc_total       8247 non-null   float64
 41  dci            8247 non-null   float64
 42  dcmi           8247 non-null   float64
 43  dif_duo        8247 non-null   int64
dtypes: float64(35), int64(2), object(7)
memory usage: 2.8+ MB

In [ ]:
existe_string = dados_brutos.map(lambda x: isinstance(x, str)).any().any()
print(existe_string)

True

## A base de dados possui incoerencia do tipo:

- mistura de tipos de dados em uma mesma coluna
- inconsistências de registro

In [ ]:
# colunas com dados tipo str()

# mascara booleana novamente
mascara_string = dados_brutos.map(lambda x: isinstance(x, str))

# quais colunas possuem ao menos uma string
colunas_com_string = mascara_string.any()
colunas_alvo = colunas_com_string[colunas_com_string].index.tolist()

print(f"Colunas com strings detectadas: {colunas_alvo}")

# Para cada coluna detectada, mostramos os valores únicos que são strings
for col in colunas_alvo:
    # Filtramos apenas as células que são strings naquela coluna específica
    valores_encontrados = dados_brutos.loc[mascara_string[col], col].unique()
    print(f"-> Na coluna '{col}', encontramos: {valores_encontrados}\n")

Colunas com strings detectadas: ['nome_sessao', 'quarto_jg', 'vel_max', 'adversario', 'idade', 'tempo', 'temp']
-> Na coluna 'nome_sessao', encontramos: ['22.10.15_Flamengo' '22.10.18_Pinheiros' '22.10.20_Bauru'
 '22.10.24_Franca' '22.10.28_Caxias' '22.11.05_União Corinthians'
 '22.11.17_Cerrado' '22.11.19_Brasilia' '22.11.23_São José'
 '22.11.29_Fortaleza' '22.12.03_Paulistano' '22.12.08_Rio Claro'
 '22.12.19_Corinthians' '22.12.21_Pato' '22.12.27_São Paulo'
 '23.01.06_Unifacisa' '23.01.10_Bauru' '23.01.12_Pinheiros'
 '23.01.30_São José' '23.02.10_Caxias' '23.02.12_União Corinthians'
 '23.02.15_Cerrado' '23.02.17_Brasilia' '23.03.01_Flamengo'
 '23.03.14_São Paulo' '23.03.21_Franca' '23.03.23_Rio Claro'
 '23.03.28_Corinthians' '23.03.31_Pato' '23.04.03_Paulistano'
 '23.04.06_Unifacisa' '23.04.08_Fortaleza' '23.04.27_Paulistano'
 '23.04.30_Paulistano' '23.05.02_Paulistano' '23.05.07_Paulistano'
 '23.05.09_Paulistano' '23.05.13_Franca' '23.05.16_Franca'
 '23.05.18_Franca' '23.05.21_Franca' '23.05.23_Franca' '23.10.13_Flamengo'
 '23.10.21_Botafogo' '23.10.23_Vasco' '23.11.08_São José' '23.11.10_Mogi'
 '23.11.16_Bauru' '23.11.18_Franca' '23.11.23_São Paulo'
 '23.11.25_Paulistano' '23.11.29_Unifacisa' '23.12.01_Fortaleza'
 '23.12.06_Cerrado' '23.12.14_Corinthians' '23.12.16_Pinheiros'
 '23.12.20_Brasilia' '23.12.22_Pato' '23.12.27_Caxias do Sul'
 '23.12.29_União Corinthians' '24.01.08_Botafogo' '24.01.11_Flamengo'
 '24.01.13_Vasco' '24.01.17_Brasilia' '24.01.19_Cerrado' '24.02.08_Mogi'
 '24.02.15_São Paulo' '24.02.29_Franca' '24.03.02_Bauru'
 '24.03.11_Paulistano' '24.03.20_Fortaleza' '24.03.22_Unifacisa'
 '24.03.25_São José' '24.03.27_Pinheiros' '24.03.30_Corinthians'
 '24.04.05_Pato' '24.04.10_Caxias' '24.04.12_União Corinthians'
 '24.04.19_União Corinthians' '24.04.23_União Corinthians'
 '24.05.03_São Paulo' '24.05.06_São Paulo' '24.05.08_São Paulo'
 '24.05.11_São Paulo' '24.05.13_São Paulo' '24.05.17_Franca'
 '24.05.20_Franca' '24.05.22_Franca' '24.05.25_Franca' '24.05.27_Franca'
 '24.10.12_Brasilia' '24.10.15_Franca' '24.10.17_Bauru'
 '24.10.21_São José' '24.10.24_Mogi' '24.10.29_Pinheiros'
 '24.10.31_Corinthians' '24.11.07_Fortaleza' '24.11.11_Unifacisa'
 '24.11.14_UniaoCor.' '24.11.16_Caxias' '24.11.30_Flamengo'
 '24.12.02_Botafogo' '24.12.05_Pato' '24.12.09_Vasco'
 '24.12.20_Paulistano' '24.12.23_São Paulo' '24.12.27_Bauru'
 '24.12.29_Franca' '25.01.20_São José' '25.01.22_Mogi'
 '25.02.13_Corinthians' '25.02.15_Pinheiros' '25.02.28_Fortaleza'
 '25.03.03_Unifacisa' '25.03.19_Flamengo' '25.03.26_Caxias'
 '25.03.29_União Corinthians' '25.04.01_Brasilia' '25.04.03_Pato'
 '25.04.07_Vasco' '25.04.09_Botafogo' '25.04.12_São Paulo'
 '25.04.14_Paulistano' '25.04.26_Mogi' '25.04.29_Mogi' '25.05.01_Mogi'
 '25.05.09_Vasco' '25.05.12_Vasco' '25.05.14_Vasco' '25.05.23_Bauru'
 '25.05.26_Bauru' '25.05.28_Bauru' '25.06.07_Franca' '25.06.12_Franca'
 '25.06.14_Franca' '25.06.18_Franca' '25.10.18_Corinthians'
 '25.10.20_São José' '25.10.23_Mogi' '25.10.27_Pato' '25.11.01_Cruzeiro'
 '25.11.04_Franca' '25.11.08_Rioclaro' '25.11.10_Brasília'
 '25.11.15_Osasco' '25.11.18_Paulistano' '25.11.21_Pinheiros'
 '25.11.23_Bauru' '25.12.03_Caxias' '25.12.05_Unico' '25.12.18_Botafogo'
 '25.12.21_Vasco' '25.12.23_Flamengo' '25.12.27_Fortaleza'
 '25.12.29_Unifacisa' '26.01.08_Corinthians' '26.01.10_Mogi'
 '26.01.19_SãoJosé' '26.01.21_Pato' '26.02.10_Bauru' '26.02.12_Franca'
 '26.02.17_Brasília' '26.02.19_RioClaro' '26.02.22_Paulistano'
 '26.03.17_UniãoCorinthians' '26.03.19_Caxias' '26.03.22_Osasco'
 '26.03.24_Pinheiros' '26.04.01_Cruzeiro' '26.04.04_Vasco'
 '26.04.06_Flamengo' '26.04.09_Botafogo' '26.04.12_Unifacisa'
 '26.04.14_Fortaleza' '26.04.21_Cruzeiro' '26.04.24_Cruzeiro'
 '26.04.26_Cruzeiro' '26.04.29_Cruzeiro' '26.05.04_Corinthians'
 '26.05.07_Corinthians' '26.05.09_Corinthians' '26.05.12_Corinthians']

-> Na coluna 'quarto_jg', encontramos: ['1º Quarto' '2º Quarto' '3º Quarto' '4º Quarto']

-> Na coluna 'vel_max', encontramos: ['9,3' '7,1' '6,9' '7,3' '6,5' '5,2' '8,7' '7,4' '7' '26,9' '27' '26,7'
 '25,6' '27,9' '25,1' '26,8' '23,9' '25,9' '26,3' '25,5' '25,7' '25,8'
 '26' '23,2' '26,2' '26,6' '23,3' '24,6' '22,3' '21,8' '21,5' '24,4'
 '21,7' '20,5' '19,8' '15,9' '5,1' '6' '10,4' '6,7' '12,2' '5' '6,8' '4,6'
 '8,1' '20,8' '26,5' '23,1' '24,3' '21' '21,6' '28,9' '29,6' '24,7' '22,8'
 '27,4' '26,1' '26,4' '27,5' '27,1' '27,8' '11,8' '8,9' '7,8' '5,6' '7,5'
 '7,2' '12,3' '24' '22,2' '22,6' '21,2' '23' '28,6' '28,2' '20,3' '23,8'
 '5,5' '5,8' '7,7' '6,4' '5,4' '11' '6,1' '10,8' '20,4' '20,6' '24,1' '19'
 '29,4' '21,9' '19,2' '23,7' '22,5' '25,3' '6,2' '6,3' '5,3' '10,5' '15,1'
 '10,9' '18,3' '4,2' '21,1' '25,2' '28,1' '23,4' '30,3' '10,2' '7,6'
 '10,6' '17,5' '24,2' '31,1' '27,2' '23,6' '20,1' '22,7' '6,6' '11,3' '0'
 '19,1' '21,3' '31,2' '27,3' '13,1' '17,3' '19,5' '20' '24,5' '29' '27,6'
 '9,5' '7,9' '11,9' '24,9' '23,5' '22,9' '29,8' '30,9' '20,2' '29,5'
 '29,2' '10,1' '5,7' '8,4' '13,3' '11,5' '16' '25,4' '14,4' '9,2' '33,4'
 '18' '16,5' '20,7' '18,2' '29,3' '22,1' '20,9' '21,4' '9,8' '4,8' '4,9'
 '28,5' '22' '29,7' '8,8' '8' '11,2' '24,8' '22,4' '25' '8,6' '5,9' '9'
 '18,5' '18,1' '19,4' '19,9' '8,3' '8,2' '18,6' '4,1' '18,8' '17,8' '11,6'
 '11,7' '19,7' '19,6' '3,9' '9,7' '27,7' '28,3' '12' '2,2' '14,9' '18,4'
 '9,1' '10,3' '13,6' '28,7' '28,4' '10' '29,9' '12,7' '14,8' '17,4' '18,7'
 '14,1' '18,9' '30,1' '17,9' '13,7' '15,3' '13,5' '4,5' '17,7' '16,1' '28'
 '19,3' '15,6' '14,3' '14' '10,7' '15,5' '9,9' '16,4' '17' '4,3' '8,5'
 '13,8' '11,1' '13,2' '11,4' '17,1' '9,4' '12,1' '16,2' '16,7' '14,6'
 '14,5' '15,7' '17,6' '13' '16,8' '4,7' '16,9' '28,8' '29,1' '15,4' '4,4'
 '12,6' '15,8' '15,2' '9,6' '14,7' '12,9' '12,8' '17,2' '12,4' '31,3' '34'
 '32' '13,9' '13,4' '16,3' '4' '16,6' '3,7' '30,6' '33' '3,6' '2,3' '30,7'
 '3,8' '30,5' '30,4' '15' '31' '14,2' '3,2' '3,5' '30']

-> Na coluna 'adversario', encontramos: ['Flamengo' 'Pinheiros' 'Bauru' 'Franca' 'Caxias' 'União Corinthians'
 'Cerrado' 'Brasilia' 'São José' 'Fortaleza' 'Paulistano' 'Rio Claro'
 'Corinthians' 'Pato' 'São Paulo' 'Unifacisa' 'Botafogo' 'Vasco' 'Mogi'
 'Cruzeiro' 'Rioclaro' 'Brasília' 'Osasco' 'UniãoCorinthians' 'SãoJosé'
 'RioClaro']

-> Na coluna 'idade', encontramos: ['20,00' '19,00' '28,00' '27,00' '30,00' '33,00' '32,00' '25,00' '26,00'
 '31,00' '21,00' '34,00' '29,00' '18,00' '24,00' '35,00' '16,00' '22,00'
 '17,00' '36,00' '37,00']

-> Na coluna 'tempo', encontramos: ['0,0' '4,9' '3,1' '10,0' '1,9' '4,4' '6,5' '7,0' '2,4' '5,9' '0,6' '6,2'
 '7,6' '0,9' '9,4' '7,1' '5,6' '2,6' '7,4' '4,0' '6,0' '7,2' '6,4' '8,3'
 '3,6' '3,8' '3,7' '2,2' '3,0' '3,2' '3,5' '4,1' '4,6' '4,7' '5,0' '5,1'
 '6,6' '6,8' '7,5' '7,8' '7,9' '8,4' '8,9' '9,2' '9,3' '1,8' '2,5' '3,4'
 '5,2' '6,1' '6,3' '7,3' '9,7' '1,4' '1,5' '5,8' '6,9' '8,1' '8,5' '8,6'
 '9,5' '1,1' '2,1' '3,3' '4,2' '5,4' '5,5' '5,7' '6,7' '1,6' '1,7' '2,0'
 '4,3' '8,0' '9,9' '0,8' '2,8' '0,3' '2,3' '2,9' '5,3' '7,7' '4,5' '4,8'
 '0,2' '0,4' '1,3' '8,7' '9,1' '9,6' '9,8' '1,2' '8,8' '3,9' '1,0' '9,0'
 '0,1' '2,7' '0,5' '0,7' '8,2' '0' '3' '1' '8' '10' '7' '6' '4' '5' '2'
 '9']

-> Na coluna 'temp', encontramos: ['22_23' '23_24' '24_25' '25_26']

##Tratamento por coluna com inconsistências

### **quarto_jg**

transfomações:

Jogo completo = 0

1º Quarto = 1

2º Quarto = 2

3º Quarto = 3

4º Quarto = 4

5º Quarto = 5  

6º Quarto = 6

In [ ]:
mapa_quartos_jogo = {
    'Jogo completo': 0,
    '1º Quarto': 1,
    '2º Quarto': 2,
    '3º Quarto': 3,
    '4º Quarto': 4,
    '5º Quarto': 5,
    '6º Quarto': 6
}

dados_brutos['quarto_jg'] = dados_brutos['quarto_jg'].map(mapa_quartos_jogo)

dados_brutos['quarto_jg'].info()
#Na proxima etapa da analise é necessario transformar esse dado em fator

<class 'pandas.core.series.Series'>
Index: 8247 entries, 2638 to 11812
Series name: quarto_jg
Non-Null Count  Dtype
--------------  -----
8247 non-null   int64
dtypes: int64(1)
memory usage: 128.9 KB

In [ ]:
dados_brutos['quarto_jg'].unique()

array([1, 2, 3, 4])

### **vel_max**

Transformações:

- substituição de vírgula por ponto

In [ ]:
dados_brutos['vel_max'] = dados_brutos['vel_max'].str.replace(',', '.')

In [ ]:
#transformando a coluna vel_max em float()
dados_brutos['vel_max'] = dados_brutos['vel_max'].astype(float)

### **adversario**

Transformações:

'Flamengo' = 'flameng'

'Pato' = 'pato'

'Campo Mourão' = 'camp_mour'

'Fortaleza' = 'fortalez'

'Unifacisa' = 'unifac'

'Bauru' = 'bauru'

'Brasilia' = 'brasil'

'Caxias do Sul' = 'caxias_sul'

'Cerrado' = 'cerr'

'Mogi' = 'mogi'

'São Paulo' = 'sp'

'Pinheiros' = 'pinheir'

'Franca' = 'franc'

'Paulistano' = 'paulist'

'Corinthians' = 'corint'

' Franca' = 'franc'

'Rio Claro' = 'rio_cl'

'União Corinthians' = 'uniao_corint'

'Caxias' = 'caxias'

'São José' = 'sao_jos'

'Botafogo' = 'botaf'

'Vasco' = 'vasc'

In [ ]:
mapa_adversario = {
'Flamengo' : 'flameng',
'Pato' : 'pato',
'Campo Mourão' : 'camp_mour',
'Fortaleza' : 'fortalez',
'Unifacisa' : 'unifac',
'Bauru' : 'bauru',
'Brasilia' : 'brasil',
'Caxias do Sul' : 'caxias_sul',
'Cerrado' : 'cerr',
'Mogi' : 'mogi',
'São Paulo' : 'sp',
'Pinheiros' : 'pinheir',
'Franca' : 'franc',
'Paulistano' : 'paulist',
'Corinthians' : 'corint',
' Franca' : 'franc',
'Rio Claro' : 'rio_cl',
'União Corinthians' : 'uniao_corint',
'Caxias' : 'caxias',
'São José' : 'sao_jos',
'Botafogo' : 'botaf',
'Vasco' : 'vasc'}

In [ ]:
dados_brutos['adversario'] = dados_brutos['adversario'].map(mapa_adversario)

In [ ]:
dados_brutos['adversario'].unique()

array(['flameng', 'pinheir', 'bauru', 'franc', 'caxias', 'uniao_corint',
       'cerr', 'brasil', 'sao_jos', 'fortalez', 'paulist', 'rio_cl',
       'corint', 'pato', 'sp', 'unifac', 'botaf', 'vasc', 'mogi', nan],
      dtype=object)

### **idade**

transformações:

- para dados do tipo int()

In [ ]:
dados_brutos['idade'] = dados_brutos['idade'].str.replace(',', '.')

In [ ]:
dados_brutos['idade'] = dados_brutos['idade'].astype(float).round().astype(int)

In [ ]:
dados_brutos['idade'].unique()

array([20, 19, 28, 27, 30, 33, 32, 25, 26, 31, 21, 34, 29, 18, 24, 35, 16,
       22, 17, 36, 37])

### **tempo**

tranformações:

- trocar vírgula por ponto
- retirando informações **nan**

In [ ]:
dados_brutos['tempo'] = dados_brutos['tempo'].str.replace(',', '.')

In [ ]:
dados_brutos['tempo'].describe()

count     8214
unique     112
top          0
freq      1216
Name: tempo, dtype: object

In [ ]:
dados_brutos['tempo'].unique()

array(['0.0', '4.9', '3.1', '10.0', '1.9', '4.4', '6.5', '7.0', '2.4',
       '5.9', '0.6', '6.2', '7.6', '0.9', '9.4', '7.1', '5.6', '2.6',
       '7.4', '4.0', '6.0', '7.2', '6.4', '8.3', '3.6', '3.8', '3.7',
       '2.2', '3.0', '3.2', '3.5', '4.1', '4.6', '4.7', '5.0', '5.1',
       '6.6', '6.8', '7.5', '7.8', '7.9', '8.4', '8.9', '9.2', '9.3',
       '1.8', '2.5', '3.4', '5.2', '6.1', '6.3', '7.3', '9.7', '1.4',
       '1.5', '5.8', '6.9', '8.1', '8.5', '8.6', '9.5', '1.1', '2.1',
       '3.3', '4.2', '5.4', '5.5', '5.7', '6.7', '1.6', '1.7', '2.0',
       '4.3', '8.0', '9.9', '0.8', '2.8', '0.3', '2.3', '2.9', '5.3',
       '7.7', '4.5', '4.8', '0.2', '0.4', '1.3', '8.7', '9.1', '9.6',
       '9.8', '1.2', '8.8', '3.9', '1.0', '9.0', '0.1', '2.7', '0.5',
       '0.7', '8.2', '0', '3', '1', '8', '10', '7', '6', '4', '5', '2',
       '9', nan], dtype=object)

In [ ]:
dados_brutos['tempo'].isnull().sum()

np.int64(33)

In [ ]:
#tranformando a coluna dados no tipo float()
dados_brutos['tempo'] = dados_brutos['tempo'].astype(float)

### **mando, posição, interv_dias, classificação, idade, dif, nome_sessao**

- Verificação dessas colunas em especial

In [ ]:
# tipo de dados da coluna mando
# mando tem dois niveis: 1 = fora e 2 = casa
dados_brutos['mando'].info()

<class 'pandas.core.series.Series'>
Index: 8247 entries, 2638 to 11812
Series name: mando
Non-Null Count  Dtype
--------------  -----
8247 non-null   float64
dtypes: float64(1)
memory usage: 128.9 KB

In [ ]:
dados_brutos['mando'].isnull().sum()

np.int64(0)

In [ ]:
# tipo de dado da coluna posição
# a posição foi classificado nos niveis: 3 = armadores, 2 = pivos e 1 = alas
dados_brutos['posicao'].unique()

array([3., 1., 2.])

In [ ]:
# tipo de dado da coluna interv_dia
dados_brutos['interv_dias'].isnull().sum() #??????

np.int64(88)

In [ ]:
dados_brutos['classificacao'].isnull().sum()

np.int64(0)

In [ ]:
dados_brutos = dados_brutos.dropna(subset=['classificacao'])

In [ ]:
# tipo de dado da coluna classificação
dados_brutos['classificacao'].info() # o tipo de dado de classificação tem que ser inteiro int(64)

<class 'pandas.core.series.Series'>
Index: 8203 entries, 2638 to 11812
Series name: classificacao
Non-Null Count  Dtype
--------------  -----
8203 non-null   float64
dtypes: float64(1)
memory usage: 128.2 KB

In [ ]:
# modificando o tipo de dado da coluna classificação
dados_brutos['classificacao'] = dados_brutos['classificacao'].astype(int)
dados_brutos['classificacao'].info()

<class 'pandas.core.series.Series'>
Index: 8203 entries, 2638 to 11812
Series name: classificacao
Non-Null Count  Dtype
--------------  -----
8203 non-null   int64
dtypes: int64(1)
memory usage: 128.2 KB

In [ ]:
dados_brutos['classificacao'].describe().round(2) # a classificação vai de 1 a 19 memso?

count    8203.00
mean        9.12
std         5.56
min         1.00
25%         4.00
50%         9.00
75%        14.00
max        20.00
Name: classificacao, dtype: float64

In [ ]:
# tipo de dado da coluna idade
dados_brutos['idade'].info()

<class 'pandas.core.series.Series'>
Index: 8203 entries, 2638 to 11812
Series name: idade
Non-Null Count  Dtype
--------------  -----
8203 non-null   int64
dtypes: int64(1)
memory usage: 128.2 KB

In [ ]:
# tipo de dado da coluna dif
dados_brutos['dif'].describe()

count    8203.000000
mean        7.963794
std        14.415678
min       -31.000000
25%        -2.000000
50%         8.000000
75%        18.000000
max        51.000000
Name: dif, dtype: float64

In [ ]:
dados_brutos['dif'].unique()

array([-12.,  -9.,  10.,  -2.,   6.,  20.,  51.,   8., -17.,  29.,  14.,
         1.,   5.,   7.,   4.,  31.,  -1.,  11.,  -4.,  18.,   2.,  -8.,
        35., -10.,   9.,   3., -15., -14.,  17.,  12.,  19.,  15.,  30.,
        24.,  37.,  43.,  13.,  25., -31., -24.,  -6.,  27.,  26.,  22.,
        38.,  23., -16., -13.,  16.,  34., -18., -21.,  21.,  -3., -11.])

In [ ]:
dados_brutos['dif'].info()

<class 'pandas.core.series.Series'>
Index: 8203 entries, 2638 to 11812
Series name: dif
Non-Null Count  Dtype
--------------  -----
8203 non-null   float64
dtypes: float64(1)
memory usage: 128.2 KB

In [ ]:
# tipo de dado da coluna nome_sessao
dados_brutos['nome_sessao'].describe()

count                   8203
unique                   182
top       24.11.07_Fortaleza
freq                      52
Name: nome_sessao, dtype: object

### **Segunda verificação de inconsistencias**

In [ ]:
# colunas com dados tipo str()

# mascara booleana novamente
mascara_string = dados_brutos.map(lambda x: isinstance(x, str))

# quais colunas possuem ao menos uma string
colunas_com_string = mascara_string.any()
colunas_alvo = colunas_com_string[colunas_com_string].index.tolist()

print(f"Colunas com strings detectadas: {colunas_alvo}")

# Para cada coluna detectada, mostramos os valores únicos que são strings
for col in colunas_alvo:
    # Filtramos apenas as células que são strings naquela coluna específica
    valores_encontrados = dados_brutos.loc[mascara_string[col], col].unique()
    print(f"-> Na coluna '{col}', encontramos: {valores_encontrados}\n")

Colunas com strings detectadas: ['nome_sessao', 'adversario', 'temp']
-> Na coluna 'nome_sessao', encontramos: ['22.10.15_Flamengo' '22.10.18_Pinheiros' '22.10.20_Bauru'
 '22.10.24_Franca' '22.10.28_Caxias' '22.11.05_União Corinthians'
 '22.11.17_Cerrado' '22.11.19_Brasilia' '22.11.23_São José'
 '22.11.29_Fortaleza' '22.12.03_Paulistano' '22.12.08_Rio Claro'
 '22.12.19_Corinthians' '22.12.21_Pato' '22.12.27_São Paulo'
 '23.01.06_Unifacisa' '23.01.10_Bauru' '23.01.12_Pinheiros'
 '23.01.30_São José' '23.02.10_Caxias' '23.02.12_União Corinthians'
 '23.02.15_Cerrado' '23.02.17_Brasilia' '23.03.01_Flamengo'
 '23.03.14_São Paulo' '23.03.21_Franca' '23.03.23_Rio Claro'
 '23.03.28_Corinthians' '23.03.31_Pato' '23.04.03_Paulistano'
 '23.04.06_Unifacisa' '23.04.08_Fortaleza' '23.04.27_Paulistano'
 '23.04.30_Paulistano' '23.05.02_Paulistano' '23.05.07_Paulistano'
 '23.05.09_Paulistano' '23.05.13_Franca' '23.05.16_Franca'
 '23.05.18_Franca' '23.05.21_Franca' '23.05.23_Franca' '23.10.13_Flamengo'
 '23.10.21_Botafogo' '23.10.23_Vasco' '23.11.08_São José' '23.11.10_Mogi'
 '23.11.16_Bauru' '23.11.18_Franca' '23.11.23_São Paulo'
 '23.11.25_Paulistano' '23.11.29_Unifacisa' '23.12.01_Fortaleza'
 '23.12.06_Cerrado' '23.12.14_Corinthians' '23.12.16_Pinheiros'
 '23.12.20_Brasilia' '23.12.22_Pato' '23.12.27_Caxias do Sul'
 '23.12.29_União Corinthians' '24.01.08_Botafogo' '24.01.11_Flamengo'
 '24.01.13_Vasco' '24.01.17_Brasilia' '24.01.19_Cerrado' '24.02.08_Mogi'
 '24.02.15_São Paulo' '24.02.29_Franca' '24.03.02_Bauru'
 '24.03.11_Paulistano' '24.03.20_Fortaleza' '24.03.22_Unifacisa'
 '24.03.25_São José' '24.03.27_Pinheiros' '24.03.30_Corinthians'
 '24.04.05_Pato' '24.04.10_Caxias' '24.04.12_União Corinthians'
 '24.04.19_União Corinthians' '24.04.23_União Corinthians'
 '24.05.03_São Paulo' '24.05.06_São Paulo' '24.05.08_São Paulo'
 '24.05.11_São Paulo' '24.05.13_São Paulo' '24.05.17_Franca'
 '24.05.20_Franca' '24.05.22_Franca' '24.05.25_Franca' '24.05.27_Franca'
 '24.10.12_Brasilia' '24.10.15_Franca' '24.10.17_Bauru'
 '24.10.21_São José' '24.10.24_Mogi' '24.10.29_Pinheiros'
 '24.10.31_Corinthians' '24.11.07_Fortaleza' '24.11.11_Unifacisa'
 '24.11.14_UniaoCor.' '24.11.16_Caxias' '24.11.30_Flamengo'
 '24.12.02_Botafogo' '24.12.05_Pato' '24.12.09_Vasco'
 '24.12.20_Paulistano' '24.12.23_São Paulo' '24.12.27_Bauru'
 '24.12.29_Franca' '25.01.20_São José' '25.01.22_Mogi'
 '25.02.13_Corinthians' '25.02.15_Pinheiros' '25.02.28_Fortaleza'
 '25.03.03_Unifacisa' '25.03.19_Flamengo' '25.03.26_Caxias'
 '25.03.29_União Corinthians' '25.04.01_Brasilia' '25.04.03_Pato'
 '25.04.07_Vasco' '25.04.09_Botafogo' '25.04.12_São Paulo'
 '25.04.14_Paulistano' '25.04.26_Mogi' '25.04.29_Mogi' '25.05.01_Mogi'
 '25.05.09_Vasco' '25.05.12_Vasco' '25.05.14_Vasco' '25.05.23_Bauru'
 '25.05.26_Bauru' '25.05.28_Bauru' '25.06.07_Franca' '25.06.12_Franca'
 '25.06.14_Franca' '25.06.18_Franca' '25.10.18_Corinthians'
 '25.10.23_Mogi' '25.10.27_Pato' '25.11.01_Cruzeiro' '25.11.04_Franca'
 '25.11.08_Rioclaro' '25.11.10_Brasília' '25.11.15_Osasco'
 '25.11.18_Paulistano' '25.11.21_Pinheiros' '25.11.23_Bauru'
 '25.12.03_Caxias' '25.12.05_Unico' '25.12.18_Botafogo' '25.12.21_Vasco'
 '25.12.23_Flamengo' '25.12.27_Fortaleza' '25.12.29_Unifacisa'
 '26.01.08_Corinthians' '26.01.10_Mogi' '26.01.19_SãoJosé' '26.01.21_Pato'
 '26.02.10_Bauru' '26.02.12_Franca' '26.02.17_Brasília'
 '26.02.19_RioClaro' '26.02.22_Paulistano' '26.03.17_UniãoCorinthians'
 '26.03.19_Caxias' '26.03.22_Osasco' '26.03.24_Pinheiros'
 '26.04.01_Cruzeiro' '26.04.04_Vasco' '26.04.06_Flamengo'
 '26.04.09_Botafogo' '26.04.12_Unifacisa' '26.04.14_Fortaleza'
 '26.04.21_Cruzeiro' '26.04.24_Cruzeiro' '26.04.26_Cruzeiro'
 '26.04.29_Cruzeiro' '26.05.04_Corinthians' '26.05.07_Corinthians'
 '26.05.09_Corinthians' '26.05.12_Corinthians']

-> Na coluna 'adversario', encontramos: ['flameng' 'pinheir' 'bauru' 'franc' 'caxias' 'uniao_corint' 'cerr'
 'brasil' 'sao_jos' 'fortalez' 'paulist' 'rio_cl' 'corint' 'pato' 'sp'
 'unifac' 'botaf' 'vasc' 'mogi']

-> Na coluna 'temp', encontramos: ['22_23' '23_24' '24_25' '25_26']

In [ ]:
# Encontrando valores 0 na coluna tempo
tabela_tempo_0 = dados_brutos[dados_brutos['tempo'] == 0]

In [ ]:
tabela_tempo_0.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1701 entries, 2638 to 11809
Data columns (total 44 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   npf            1701 non-null   int64
 1   nome_sessao    1701 non-null   object
 2   quarto_jg      1701 non-null   int64
 3   vel_max        1701 non-null   float64
 4   dits_total     1701 non-null   float64
 5   sprints        1701 non-null   float64
 6   zv1            1701 non-null   float64
 7   zv2            1701 non-null   float64
 8   zv3            1701 non-null   float64
 9   zv4            1701 non-null   float64
 10  zv5            1701 non-null   float64
 11  dcel1          1701 non-null   float64
 12  dcel2          1701 non-null   float64
 13  dcel3          1701 non-null   float64
 14  dcel4          1701 non-null   float64
 15  acel1          1701 non-null   float64
 16  acel2          1701 non-null   float64
 17  acel3          1701 non-null   float64
 18  acel4          1701 non-null   float64
 19  fc1            1701 non-null   float64
 20  fc2            1701 non-null   float64
 21  fc3            1701 non-null   float64
 22  fc4            1701 non-null   float64
 23  fc5            1701 non-null   float64
 24  fc_80          1701 non-null   float64
 25  trimp          1701 non-null   float64
 26  dai            1701 non-null   float64
 27  dmi            1701 non-null   float64
 28  adversario     1606 non-null   object
 29  idade          1701 non-null   int64
 30  classificacao  1701 non-null   int64
 31  interv_dias    1684 non-null   float64
 32  mando          1701 non-null   float64
 33  posicao        1701 non-null   float64
 34  dif            1701 non-null   float64
 35  tempo          1701 non-null   float64
 36  temp           1701 non-null   object
 37  ac_total       1701 non-null   float64
 38  acmi           1701 non-null   float64
 39  aci            1701 non-null   float64
 40  dc_total       1701 non-null   float64
 41  dci            1701 non-null   float64
 42  dcmi           1701 non-null   float64
 43  dif_duo        1701 non-null   int64
dtypes: float64(36), int64(5), object(3)
memory usage: 598.0+ KB

O que deve ser feito quando o tempo == 0 no data set?

eu retirei todas

In [ ]:
dados_brutos = dados_brutos[dados_brutos['tempo'] > 1].copy()

In [ ]:
#exportando base de dados brutos tratados
dados_brutos.to_csv('base_dados_brutos_tratados.csv', index=False)

## Contrução da base de dados derivada

In [ ]:
df = pd.DataFrame()

In [ ]:
df['npf'] = dados_brutos['npf']
df['quarto_jg'] = dados_brutos['quarto_jg']
df['vel_max'] = dados_brutos['vel_max']
df['adversario'] = dados_brutos['adversario']
df['idade'] = dados_brutos['idade']
df['classificacao'] = dados_brutos['classificacao']
df['interv_dias'] = dados_brutos['interv_dias']
df['mando'] = dados_brutos['mando']
df['posicao'] = dados_brutos['posicao']
df['idade'] = dados_brutos['idade']
df['dif'] = dados_brutos['dif']
df['nome_sessao'] = dados_brutos['nome_sessao']
df['tempo'] = dados_brutos['tempo']
df['temp'] = dados_brutos['temp']
df['sprints'] = dados_brutos['sprints']/ dados_brutos['tempo']
df['zv1_min'] = dados_brutos['zv1']/ dados_brutos['tempo']
df['zv2_min'] = dados_brutos['zv2']/ dados_brutos['tempo']
df['zv3_min'] = dados_brutos['zv3']/ dados_brutos['tempo']
df['zv4_min'] = dados_brutos['zv4']/ dados_brutos['tempo']
df['zv5_min'] = dados_brutos['zv5']/ dados_brutos['tempo']
df['dcel1_min'] = dados_brutos['dcel1']/ dados_brutos['tempo']
df['dcel2_min'] = dados_brutos['dcel2']/ dados_brutos['tempo']
df['dcel3_min'] = dados_brutos['dcel3']/ dados_brutos['tempo']
df['dcel4_min'] = dados_brutos['dcel4']/ dados_brutos['tempo']
df['acel1_min'] = dados_brutos['acel1']/ dados_brutos['tempo']
df['acel2_min'] = dados_brutos['acel2']/ dados_brutos['tempo']
df['acel3_min'] = dados_brutos['acel3']/ dados_brutos['tempo']
df['acel4_min'] = dados_brutos['acel4']/ dados_brutos['tempo']
df['fc1_min'] = dados_brutos['fc1']/ dados_brutos['tempo']
df['fc2_min'] = dados_brutos['fc2']/ dados_brutos['tempo']
df['fc3_min'] = dados_brutos['fc3']/ dados_brutos['tempo']
df['fc4_min'] = dados_brutos['fc4']/ dados_brutos['tempo']
df['fc5_min'] = dados_brutos['fc5']/ dados_brutos['tempo']
df['fc_80_min'] = dados_brutos['fc_80']/ dados_brutos['tempo']
df['trimp_min'] = dados_brutos['trimp']/ dados_brutos['tempo']
df['dits_total_min'] = dados_brutos['dits_total']/ dados_brutos['tempo']
df['dai_min'] = dados_brutos['dai']/ dados_brutos['tempo']
df['dmi_min'] = dados_brutos['dmi']/ dados_brutos['tempo']

In [ ]:
df['ac_total_min'] = dados_brutos['ac_total']/ dados_brutos['tempo']
df['acmi_min'] = dados_brutos['acmi']/ dados_brutos['tempo']
df['aci_min'] = dados_brutos['aci']/ dados_brutos['tempo']
df['dc_total_min'] = dados_brutos['dc_total']/ dados_brutos['tempo']
df['dcmi_min'] = dados_brutos['dcmi']/ dados_brutos['tempo']
df['dci_min'] = dados_brutos['dci']/ dados_brutos['tempo']

Análises sugeridas pelo Samu: Dicotomizar a base de dados sobre para a dif (5pts em modolo) e interv_dias (>= 2 e <= 3)

In [ ]:
# Se 'dif' for maior que 5 OU menor que -5, recebe 1. Caso contrário, recebe 2.
df['dif_duo'] = np.where((df['dif'] >= 5) | (df['dif'] <= -5), 1, 2)

In [ ]:
# Se 'interv_dias' for menor ou igual a 2, recebe 1. Caso contrário, recebe 2.
df['interv_duo'] = np.where((df['dif'] < 2), 1, 2)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6284 entries, 2647 to 11811
Data columns (total 45 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   npf             6284 non-null   int64
 1   quarto_jg       6284 non-null   int64
 2   vel_max         6284 non-null   float64
 3   adversario      5728 non-null   object
 4   idade           6284 non-null   int64
 5   classificacao   6284 non-null   int64
 6   interv_dias     6217 non-null   float64
 7   mando           6284 non-null   float64
 8   posicao         6284 non-null   float64
 9   dif             6284 non-null   float64
 10  nome_sessao     6284 non-null   object
 11  tempo           6284 non-null   float64
 12  temp            6284 non-null   object
 13  sprints         6284 non-null   float64
 14  zv1_min         6284 non-null   float64
 15  zv2_min         6284 non-null   float64
 16  zv3_min         6284 non-null   float64
 17  zv4_min         6284 non-null   float64
 18  zv5_min         6284 non-null   float64
 19  dcel1_min       6284 non-null   float64
 20  dcel2_min       6284 non-null   float64
 21  dcel3_min       6284 non-null   float64
 22  dcel4_min       6284 non-null   float64
 23  acel1_min       6284 non-null   float64
 24  acel2_min       6284 non-null   float64
 25  acel3_min       6284 non-null   float64
 26  acel4_min       6284 non-null   float64
 27  fc1_min         6284 non-null   float64
 28  fc2_min         6284 non-null   float64
 29  fc3_min         6284 non-null   float64
 30  fc4_min         6284 non-null   float64
 31  fc5_min         6284 non-null   float64
 32  fc_80_min       6284 non-null   float64
 33  trimp_min       6284 non-null   float64
 34  dits_total_min  6284 non-null   float64
 35  dai_min         6284 non-null   float64
 36  dmi_min         6284 non-null   float64
 37  ac_total_min    6284 non-null   float64
 38  acmi_min        6284 non-null   float64
 39  aci_min         6284 non-null   float64
 40  dc_total_min    6284 non-null   float64
 41  dcmi_min        6284 non-null   float64
 42  dci_min         6284 non-null   float64
 43  dif_duo         6284 non-null   int64
 44  interv_duo      6284 non-null   int64
dtypes: float64(36), int64(6), object(3)
memory usage: 2.2+ MB

In [ ]:
df.head()

,npf,quarto_jg,vel_max,adversario,idade,classificacao,interv_dias,mando,posicao,dif,nome_sessao,tempo,temp,sprints,zv1_min,zv2_min,zv3_min,zv4_min,zv5_min,dcel1_min,dcel2_min,dcel3_min,dcel4_min,acel1_min,acel2_min,acel3_min,acel4_min,fc1_min,fc2_min,fc3_min,fc4_min,fc5_min,fc_80_min,trimp_min,dits_total_min,dai_min,dmi_min,ac_total_min,acmi_min,aci_min,dc_total_min,dcmi_min,dci_min,dif_duo,interv_duo
2647,709286,2,26.9,flameng,28,3,NaN,2.0,1.0,-12.0,22.10.15_Flamengo,4.9,22_23,3.265306,75.306122,88.775510,39.591837,27.346939,7.142857,11.428571,16.530612,3.061224,2.653061,10.408163,14.897959,5.714286,0.204082,1.428571,1.224490,0.612245,1.020408,0.612245,1.632653,12.857143,246.530612,34.489796,74.081633,31.224490,20.816327,5.918367,33.673469,22.244898,5.714286,1,1
2648,703092,3,27.0,flameng,27,3,NaN,2.0,3.0,-12.0,22.10.15_Flamengo,3.1,22_23,2.903226,60.322581,80.967742,33.870968,17.741935,11.935484,11.935484,12.580645,4.516129,1.935484,10.322581,14.838710,3.870968,0.000000,4.516129,0.967742,0.645161,0.645161,1.290323,1.935484,16.451613,213.548387,29.677419,63.548387,29.032258,18.709677,3.870968,30.967742,19.032258,6.451613,1,1
2649,709286,3,26.7,flameng,28,3,NaN,2.0,1.0,-12.0,22.10.15_Flamengo,10.0,22_23,3.000000,66.400000,58.000000,41.200000,17.100000,8.900000,6.500000,14.300000,3.900000,2.100000,5.200000,11.800000,6.300000,0.200000,0.200000,0.400000,0.600000,0.700000,0.500000,1.200000,7.900000,198.500000,26.000000,67.200000,23.500000,18.300000,6.500000,26.800000,20.300000,6.000000,1,1
2650,709202,2,25.6,flameng,20,3,NaN,2.0,1.0,-12.0,22.10.15_Flamengo,1.9,22_23,4.210526,66.315789,79.473684,30.000000,22.631579,2.631579,13.157895,23.684211,5.263158,0.526316,12.631579,23.684211,5.789474,0.000000,3.157895,0.526316,0.526316,1.052632,0.000000,1.052632,9.473684,214.210526,25.263158,55.263158,42.105263,29.473684,5.789474,42.631579,29.473684,5.789474,1,1
2651,709286,4,27.9,flameng,28,3,NaN,2.0,1.0,-12.0,22.10.15_Flamengo,10.0,22_23,2.200000,55.500000,61.400000,39.700000,13.000000,10.800000,8.200000,11.300000,4.000000,1.200000,6.500000,11.100000,5.000000,0.100000,0.200000,0.500000,0.500000,0.700000,0.700000,1.400000,9.200000,186.700000,23.800000,63.500000,22.700000,16.200000,5.100000,24.700000,16.500000,5.200000,1,1

In [ ]:
df['quarto_jg'].unique()

array([2, 3, 4, 1])

In [ ]:
#exportar base de dados df
df.to_csv('base_dados_derivada_min.csv', index=False)

## Contrução da base de dados de caracterização

Para caracterizar o jogo, acredito que será mais interessante unificar os quartos para analisar a partida completa

In [ ]:
dados_carac = dados_brutos

In [ ]:
dados_carac = dados_carac[dados_carac['tempo'] > 1].copy()

In [ ]:
dados_carac = dados_brutos.groupby(['npf', 'nome_sessao']).agg(
    dits_total = ('dits_total', 'sum'),
    dmi = ('dmi', 'sum'),
    dai = ('dai', 'sum'),
    zv1 = ('zv1', 'sum'),
    zv2 = ('zv2', 'sum'),
    zv3 = ('zv3', 'sum'),
    zv4 = ('zv4', 'sum'),
    zv5 = ('zv5', 'sum'),
    dcel1 = ('dcel1', 'sum'),
    dcel2 = ('dcel2', 'sum'),
    dcel3 = ('dcel3', 'sum'),
    dcel4 = ('dcel4', 'sum'),
    acel1 = ('acel1', 'sum'),
    acel2 = ('acel2', 'sum'),
    acel3 = ('acel3', 'sum'),
    acel4 = ('acel4', 'sum'),
    fc1 = ('fc1', 'sum'),
    fc2 = ('fc2', 'sum'),
    fc3 = ('fc3', 'sum'),
    fc4 = ('fc4', 'sum'),
    fc5 = ('fc5', 'sum'),
    trimp = ('trimp', 'sum'),
    tempo = ('tempo', 'sum'),
    dc_total = ('dc_total', 'sum'),
    dcmi = ('dcmi', 'sum'),
    dci = ('dci', 'sum'),
    ac_total = ('ac_total', 'sum'),
    acmi = ('acmi', 'sum'),
    aci = ('aci', 'sum'),
    temp = ('temp', 'first'),
    posicao = ('posicao', 'first'),
    mando = ('mando', 'first'),
    idade = ('idade', 'first'),
    classificacao = ('classificacao', 'first'),
    interv_dias = ('interv_dias', 'first'),
    dif_duo = ('dif_duo', 'first'),


    count_registros = ('npf', 'count') # Conta quantas linhas existiam
).reset_index()

In [ ]:
dados_carac_min = pd.DataFrame()

In [ ]:
dados_carac_min['posicao'] = dados_carac['posicao']
dados_carac_min['dits_total_min'] = dados_carac['dits_total']/ dados_carac['tempo']
dados_carac_min['dmi_min'] = dados_carac['dmi']/ dados_carac['tempo']
dados_carac_min['dai_min'] = dados_carac['dai']/ dados_carac['tempo']
dados_carac_min['trimp_min'] = dados_carac['trimp']/ dados_carac['tempo']
dados_carac_min['dc_total_min'] = dados_carac['dc_total']/ dados_carac['tempo']
dados_carac_min['dcmi_min'] = dados_carac['dcmi']/ dados_carac['tempo']
dados_carac_min['dci_min'] = dados_carac['dci']/ dados_carac['tempo']
dados_carac_min['ac_total_min'] = dados_carac['ac_total']/ dados_carac['tempo']
dados_carac_min['acmi_min'] = dados_carac['acmi']/ dados_carac['tempo']
dados_carac_min['aci_min'] = dados_carac['aci']/ dados_carac['tempo']
dados_carac_min['temp'] = dados_carac['temp']
dados_carac_min['mando'] = dados_carac['mando']
dados_carac_min['idade'] = dados_carac['idade']
dados_carac_min['classificacao'] = dados_carac['classificacao']
dados_carac_min['interv_dias'] = dados_carac['interv_dias']
dados_carac_min['dif_duo'] = dados_carac['dif_duo']
dados_carac_min['npf'] = dados_carac['npf']
dados_carac_min['tempo'] = dados_carac['tempo']
dados_carac_min['nome_sessao'] = dados_carac['nome_sessao']
dados_carac_min['zv1_min'] = dados_carac['zv1']/ dados_carac['tempo']
dados_carac_min['zv2_min'] = dados_carac['zv2']/ dados_carac['tempo']
dados_carac_min['zv3_min'] = dados_carac['zv3']/ dados_carac['tempo']
dados_carac_min['zv4_min'] = dados_carac['zv4']/ dados_carac['tempo']
dados_carac_min['zv5_min'] = dados_carac['zv5']/ dados_carac['tempo']
dados_carac_min['dcel1_min'] = dados_carac['dcel1']/ dados_carac['tempo']
dados_carac_min['dcel2_min'] = dados_carac['dcel2']/ dados_carac['tempo']
dados_carac_min['dcel3_min'] = dados_carac['dcel3']/ dados_carac['tempo']
dados_carac_min['dcel4_min'] = dados_carac['dcel4']/ dados_carac['tempo']
dados_carac_min['acel1_min'] = dados_carac['acel1']/ dados_carac['tempo']
dados_carac_min['acel2_min'] = dados_carac['acel2']/ dados_carac['tempo']
dados_carac_min['acel3_min'] = dados_carac['acel3']/ dados_carac['tempo']
dados_carac_min['acel4_min'] = dados_carac['acel4']/ dados_carac['tempo']
dados_carac_min['fc1_min'] = dados_carac['fc1']/ dados_carac['tempo']
dados_carac_min['fc2_min'] = dados_carac['fc2']/ dados_carac['tempo']
dados_carac_min['fc3_min'] = dados_carac['fc3']/ dados_carac['tempo']
dados_carac_min['fc4_min'] = dados_carac['fc4']/ dados_carac['tempo']
dados_carac_min['fc5_min'] = dados_carac['fc5']/ dados_carac['tempo']

No trecho abaixo eu fiz os calculos de média e dp das variáveis, com o total e agrupando por posição. Os calculos agrupando por quarto de jogo estão nas análises de cada base.

### Descritivos

Distâncias absolutas

In [ ]:
def formatar_media_std(x):
    # Calcula a média e desvio, tratando os valores individualmente
    m = x.mean()
    s = x.std()
    # Formata com 1 casa decimal dentro da string (f-string)
    return f"{m:.1f} ± {s:.1f}"

# Aplica o agrupamento
relatorio_final = (
dados_carac[['dits_total', 'zv3', 'dmi', 'dai']].agg(formatar_media_std),
dados_carac.groupby('posicao')[['dits_total', 'zv3', 'dmi', 'dai']].agg(formatar_media_std))

print(relatorio_final)

(dits_total    3199.0 ± 1277.9
zv3             512.8 ± 241.3
dmi             701.4 ± 358.5
dai             188.5 ± 134.5
dtype: object,               dits_total            zv3            dmi            dai
posicao
1.0      3243.5 ± 1344.5  546.1 ± 251.7  752.2 ± 365.2  206.1 ± 133.4
2.0      3194.6 ± 1094.9  453.9 ± 184.0  594.0 ± 268.3  140.2 ± 103.0
3.0      3137.8 ± 1354.7  526.2 ± 266.7  740.0 ± 405.3  213.7 ± 151.6)

Distâncias relativizadas

In [ ]:
def formatar_media_std(x):
    # Calcula a média e desvio, tratando os valores individualmente
    m = x.mean()
    s = x.std()
    # Formata com 1 casa decimal dentro da string (f-string)
    return f"{m:.1f} ± {s:.1f}"

# Aplica o agrupamento
relatorio_final = (
dados_carac_min[['dits_total_min', 'zv3_min', 'dmi_min', 'dai_min']].agg(formatar_media_std),
dados_carac_min.groupby('posicao')[['dits_total_min', 'zv3_min', 'dmi_min', 'dai_min']].agg(formatar_media_std))

print(relatorio_final)

(dits_total_min    164.4 ± 29.0
zv3_min             26.5 ± 8.4
dmi_min            36.5 ± 13.7
dai_min             10.0 ± 6.4
dtype: object,         dits_total_min     zv3_min      dmi_min     dai_min
posicao
1.0       166.7 ± 31.9  28.5 ± 8.7  39.5 ± 13.8  11.1 ± 6.7
2.0       158.2 ± 24.7  22.4 ± 6.0  29.3 ± 10.0   6.9 ± 4.8
3.0       167.7 ± 27.7  28.1 ± 8.3  39.6 ± 14.0  11.5 ± 6.5)

Acelerações absolutas

In [ ]:
def formatar_media_std(x):
    # Calcula a média e desvio, tratando os valores individualmente
    m = x.mean()
    s = x.std()
    # Formata com 1 casa decimal dentro da string (f-string)
    return f"{m:.1f} ± {s:.1f}"

# Aplica o agrupamento
relatorio_final = (
dados_carac[['ac_total', 'acel2', 'acmi', 'aci']].agg(formatar_media_std),
dados_carac.groupby('posicao')[['ac_total', 'acel2', 'acmi', 'aci']].agg(formatar_media_std)
)

print(relatorio_final)

(ac_total    501.0 ± 189.3
acel2        260.3 ± 99.3
acmi        336.0 ± 127.5
aci           75.7 ± 32.8
dtype: object,               ac_total          acel2           acmi          aci
posicao
1.0      499.8 ± 197.0  258.7 ± 100.0  335.2 ± 130.3  76.6 ± 34.3
2.0      522.3 ± 169.5   292.0 ± 95.8  366.1 ± 120.4  74.1 ± 27.5
3.0      480.3 ± 195.3   229.0 ± 91.4  305.0 ± 123.5  76.0 ± 35.6)

Acelerações relativizadas

In [ ]:
def formatar_media_std(x):
    # Calcula a média e desvio, tratando os valores individualmente
    m = x.mean()
    s = x.std()
    # Formata com 1 casa decimal dentro da string (f-string)
    return f"{m:.1f} ± {s:.1f}"

# Aplica o agrupamento
relatorio_final = (
dados_carac_min[['ac_total_min', 'acel2_min', 'acmi_min', 'aci_min']].agg(formatar_media_std),
dados_carac_min.groupby('posicao')[['ac_total_min', 'acel2_min', 'acmi_min', 'aci_min']].agg(formatar_media_std)
)

print(relatorio_final)

(ac_total_min    26.2 ± 5.5
acel2_min       13.8 ± 3.6
acmi_min        17.6 ± 4.0
aci_min          3.9 ± 0.9
dtype: object,         ac_total_min   acel2_min    acmi_min    aci_min
posicao
1.0       26.2 ± 6.3  13.8 ± 4.1  17.7 ± 4.6  3.9 ± 1.0
2.0       26.1 ± 4.3  14.7 ± 2.9  18.3 ± 3.1  3.6 ± 0.7
3.0       26.2 ± 5.4  12.7 ± 3.4  16.8 ± 3.8  4.0 ± 1.0)

Desacelerações Absolutas

In [ ]:
def formatar_media_std(x):
    # Calcula a média e desvio, tratando os valores individualmente
    m = x.mean()
    s = x.std()
    # Formata com 1 casa decimal dentro da string (f-string)
    return f"{m:.1f} ± {s:.1f}"

# Aplica o agrupamento
relatorio_final = (
dados_carac[['dc_total', 'dcel2', 'dcmi', 'dci']].agg(formatar_media_std),
dados_carac.groupby('posicao')[['dc_total', 'dcel2', 'dcmi', 'dci']].agg(formatar_media_std)
)

print(relatorio_final)

(dc_total    516.8 ± 196.8
dcel2        257.0 ± 97.0
dcmi        344.2 ± 130.1
dci           87.2 ± 36.3
dtype: object,               dc_total          dcel2           dcmi          dci
posicao
1.0      519.5 ± 206.1  257.7 ± 100.4  345.4 ± 135.2  87.6 ± 37.4
2.0      533.9 ± 175.4   275.7 ± 90.1  363.2 ± 119.1  87.5 ± 31.5
3.0      494.7 ± 202.4   236.2 ± 95.0  322.5 ± 130.6  86.3 ± 39.3)

Desacelerações relativizadas

In [ ]:
def formatar_media_std(x):
    # Calcula a média e desvio, tratando os valores individualmente
    m = x.mean()
    s = x.std()
    # Formata com 1 casa decimal dentro da string (f-string)
    return f"{m:.1f} ± {s:.1f}"

# Aplica o agrupamento
relatorio_final = (
dados_carac_min[['dc_total_min', 'dcel2_min', 'dcmi_min', 'dci_min']].agg(formatar_media_std),
dados_carac_min.groupby('posicao')[['dc_total_min', 'dcel2_min', 'dcmi_min', 'dci_min']].agg(formatar_media_std)
)

print(relatorio_final)

(dc_total_min    26.9 ± 5.5
dcel2_min       13.6 ± 3.6
dcmi_min        18.1 ± 4.1
dci_min          4.5 ± 1.0
dtype: object,         dc_total_min   dcel2_min    dcmi_min    dci_min
posicao
1.0       27.1 ± 6.3  13.7 ± 4.1  18.2 ± 4.7  4.5 ± 1.0
2.0       26.6 ± 4.3  13.9 ± 2.8  18.2 ± 3.2  4.3 ± 0.7
3.0       27.0 ± 5.3  13.1 ± 3.3  17.7 ± 3.9  4.6 ± 1.1)

In [ ]:
def formatar_media_std(x):
    # Calcula a média e desvio, tratando os valores individualmente
    m = x.mean()
    s = x.std()
    # Formata com 1 casa decimal dentro da string (f-string)
    return f"{m:.1f} ± {s:.1f}"

# Aplica o agrupamento
relatorio_final = (
dados_carac[['trimp']].agg(formatar_media_std)
)

print(relatorio_final)

trimp    198.7 ± 82.5
dtype: object

In [ ]:
def formatar_media_std(x):
    # Calcula a média e desvio, tratando os valores individualmente
    m = x.mean()
    s = x.std()
    # Formata com 1 casa decimal dentro da string (f-string)
    return f"{m:.1f} ± {s:.1f}"

# Aplica o agrupamento
relatorio_final = (
dados_carac.groupby('posicao')[['trimp']].agg(formatar_media_std)
)

print(relatorio_final)

                trimp
posicao
1.0      198.7 ± 88.1
2.0      201.3 ± 73.0
3.0      195.9 ± 83.6

In [ ]:
def formatar_media_std(x):
    # Calcula a média e desvio, tratando os valores individualmente
    m = x.mean()
    s = x.std()
    # Formata com 1 casa decimal dentro da string (f-string)
    return f"{m:.1f} ± {s:.1f}"

# Aplica o agrupamento
relatorio_final = (
dados_carac_min[['trimp_min']].agg(formatar_media_std)
)

print(relatorio_final)

trimp_min    10.2 ± 2.9
dtype: object

In [ ]:
def formatar_media_std(x):
    # Calcula a média e desvio, tratando os valores individualmente
    m = x.mean()
    s = x.std()
    # Formata com 1 casa decimal dentro da string (f-string)
    return f"{m:.1f} ± {s:.1f}"

# Aplica o agrupamento
relatorio_final = (
dados_carac_min.groupby('posicao')[['trimp_min']].agg(formatar_media_std)
)

print(relatorio_final)

          trimp_min
posicao
1.0      10.0 ± 2.6
2.0      10.1 ± 3.1
3.0      10.7 ± 2.9

In [ ]:
#exportando base de dados brutos tratados
dados_carac.to_csv('dados_carac_tratados.csv', index=False)

In [ ]:
#exportando base de dados brutos tratados
dados_carac_min.to_csv('dados_carac_min_tratados.csv', index=False)